---
title: "01-kontekst"
format: html
---

---
title: "Nacija na mreži"
author: "Luka Sikic"
date: "2025-10-07"
format: 
  html:
    toc: true
    toc-location: left
    theme: cosmo
editor: visual
---

# Uvod: dekonstrukcija hrvatske digitalne javne sfere

Suvremeni hrvatski digitalni medijski krajolik predstavlja složenu i često proturječnu sliku. To je prostor dosad neviđenog pristupa informacijama i građanskom angažmanu, no istovremeno ga karakteriziraju izražena ekonomska nesigurnost, pad povjerenja javnosti i naizgled nezaustavljivo kretanje prema senzacionalizmu. Da bi se shvatila ta stvarnost, potrebno je razumjeti  širi društveni kontekst u kojemu se taj medijski prostor nalazi. Središnji je argument ovog poglavlja da je analiza podataka, bez uvažavanje društveno-tehničkog konteksta, samo buka. Hrvatska digitalna javna sfera nije proizvod pojedinačnih uzroka, već nastaje kao rezultat triju snažnih, isprepletenih sustava. Prvi je univerzalna ekonomska logika **platformskog kapitalizma**, koja je učvrstila globalni oglašivački duopol što iz temelja preoblikuje medijske poslovne modele diljem svijeta. Drugi je specifična povijesno-politička putanja postsocijalističke države, čije jedinstveno naslijeđe državne kontrole,  proces privatizacije i ukorijenjeni politički klijentelizam stvaraju stanje "**ovisnosti o putanji**" (*path dependency*) koje ograničava današnje mogućnosti. Treći je **tehnička arhitektura** samih dominantnih platformi, čiji algoritmi nisu neutralni prijenosnici informacija, već su kodirani sa specifičnim ideološkim i komercijalnim logikama koje aktivno oblikuju javni diskurs.

Analiza bilo kojeg od ovih sustava zasebno daje iskrivljenu i nepotpunu sliku. Akutna kriza s kojom se suočava hrvatsko novinarstvo, definirana financijskom neodrživošću kvalitetnog izvještavanja ¹, strmoglavim padom povjerenja javnosti u vijesti ³ i posljedičnim strukturnim poticajem za jeftin, velikoserijski senzacionalistički sadržaj nauštrb resursno intenzivnog novinarstva u javnom interesu ⁵, nije slučajnost niti niz nepovezanih nesreća. Ona je predvidljiv, sustavni ishod stjecaja tih globalnih ekonomskih, nacionalnih političkih i tehnoloških sila. Ekonomske realnosti digitalnog oglašivačkog tržišta stvaraju pritiske koji su jedinstveno pojačani povijesnim slabostima hrvatskog medijskog sustava, a cjelokupnu dinamiku posreduje i često ubrzava operativna logika platformi koje danas čine temeljnu infrastrukturu javnog života.

Ovo poglavlje dekonstruirat će tu složenu isprepletenost. Odjeljak I, "Politička ekonomija hrvatskog klika", analizirat će ekonomske temelje suvremene industrije digitalnih vijesti, pokazujući kako globalne tržišne sile stvaraju specifične lokalne pritiske koji izravno utječu na medijski sadržaj i novinarske prakse. Odjeljak II, "Ovisnost o putanji i postojanost države", objašnjava način na koji je osjetljivost medija na te ekonomske pritiske pojačana duboko ukorijenjenom ovisnošću o putanji koja proizlazi iz postsocijalističke tranzicije, što je potaknulo sustav obilježen političkim paralelizmom, zarobljavanjem medija i kronično niskim povjerenjem javnosti. Odjeljak III, "Algoritamska arhitektura javnog diskursa", prebacit će analizu na specifične tehnološke sustave koji posreduju u tom okruženju, istražujući kako njihovi inherentni dizajni nisu neutralni, već aktivno oblikuju prirodu i kvalitetu političke komunikacije. Konačno, poglavlje zaključuje sintezom ovih nalaza i nudi niz integriranih preporuka čiji cilj nije pružanje jednostavnih rješenja, već izgradnja sustavne otpornosti unutar hrvatskog medijskog ekosustava.

---

# Odjeljak I: Politička ekonomija hrvatskog klika

Transformacija hrvatskih medija iz krajolika u kojem dominira tisak u okruženje u kojem je digitalno na prvom mjestu ne može se razumjeti bez kritičke analize njegove temeljne ekonomske strukture. Poslovni modeli koji diktiraju proizvodnju i distribuciju vijesti primarni su pokretači sadržaja, oblikujući sve, od uredničkih prioriteta do samog opstanka novinarskih institucija. Ovaj odjeljak dekonstruira političku ekonomiju hrvatskih digitalnih medija, otkrivajući sustav pod golemim pritiskom, uhvaćen između propadajućih modela prihoda iz prošlosti i nemilosrdne tržišne logike novog digitalnog ekosustava kojim dominira nekolicina globalnih platformi.

## 1.1. Od tiska do platformi

Desetljećima je poslovni model tradicionalnih medija, posebice novina, bio relativno stabilan. Djelovao je na onome što ekonomisti nazivaju "**dvostranim tržištem**", služeći dvjema različitim skupinama kupaca: prodavao je vijesti čitateljima, a pažnju tih čitatelja prodavao je oglašivačima.⁷ Prihodi od oglašavanja i naklade stvorili su financijsku osnovu koja je, u najboljem slučaju, mogla podržati resursno intenzivne oblike novinarstva. Digitalna revolucija, međutim, nepovratno je slomila taj model. Pojava internetskih platformi i e-izdanja pružila je čitateljima sveprisutan pristup vijestima, ali je također iz temelja promijenila izvore prihoda.⁷

U Hrvatskoj, kao i globalno, digitalnu transformaciju obilježila je masovna migracija publike i prihoda od oglašavanja s tiskanih na internetske platforme.⁷ Ta je promjena jasno vidljiva u podacima. Tiskani mediji pretrpjeli su trajan pad čitanosti, pretplata i prihoda od oglašavanja, trend koji je pandemija COVID-19 ozbiljno pogoršala.¹ Dok su internet i društveni mediji postali glavni izvor vijesti za veliku većinu stanovništva --- u prosjeku **89%** ispitanika posljednjih godina --- ta se publika navikla na besplatan pristup sadržaju.¹¹ To je stvorilo egzistencijalnu krizu za izdavače, prisiljavajući ih da hitno traže nove, održive digitalne poslovne modele kako bi preživjeli dok im naslijeđeni izvori prihoda opadaju ili stagniraju.⁷ Ključni je izazov to što se prihod od oglašavanja koji ih je nekoć podržavao nije jednostavno preselio s njihovih tiskanih izdanja na njihove web stranice; presreli su ga i zarobili novi, moćni posrednici.

## 1.2. Digitalni oglašivački jaz

Da bi se razumjela financijska nesigurnost hrvatskih digitalnih medija, ključno je shvatiti pojam "**digitalnog oglašivačkog jaza**". Taj se pojam odnosi na značajan i rastući jaz između ukupnog iznosa novca potrošenog na internetsko oglašavanje unutar nacionalnog tržišta i malog dijela tog prihoda koji stvarno stiže do digitalnih novinskih kuća koje proizvode sadržaj.⁸ Problem nije u tome što je oglašavanje nestalo s interneta; problem je u tome što je sustavno preusmjereno na dvije dominantne globalne platforme: **Google (Alphabet) i Meta (Facebook)**.

Ovi digitalni posrednici uspostavili su funkcionalni **duopol** nad tržištem digitalnog oglašavanja u Europi, a posebno u Hrvatskoj.⁸ Njihovi poslovni modeli izgrađeni su na masivnim ekonomijama razmjera, neusporedivim mogućnostima prikupljanja podataka i sofisticiranim, podatkovno vođenim alatima za oglašavanje poput prediktivne analitike i programatskog oglašavanja.⁹ To im omogućuje da odvoje oglašavanje od sadržaja. U tradicionalnom modelu, oglašivač je kupovao prostor pored određenog članka ili u određenoj publikaciji kako bi došao do svoje publike. U novom "oglašivačkom hranidbenom lancu", algoritmi omogućuju oglašivačima precizno ciljanje pojedinaca, u stvarnom vremenu, na bilo kojoj web stranici na koju dospiju.⁹ To čini kontekst pouzdanog novinskog brenda manje važnim od podatkovnog profila pojedinog korisnika, oduzimajući izdavačima vijesti njihovu temeljnu vrijednost za oglašivače.

Razmjeri ovog otimanja prihoda u Hrvatskoj su zapanjujući. Prema studiji IAB Online Media AdEx, vrijednost hrvatskog tržišta internetskog oglašavanja u 2024. godini procjenjuje se na više od **155 milijuna eura**. Od tog ukupnog iznosa, oglašavanje na društvenim mrežama (34,6%) i oglašavanje na tražilicama (17,3%) zajedno čine **51,9%** svih ulaganja.¹² Unutar sfere društvenih medija, Metine platforme su apsolutno dominantne, pri čemu Facebook drži udio od 51,5%, a Instagram 43,5%, što čini ukupno **95%** potrošnje na oglašavanje na društvenim mrežama.¹² Slično tome, globalne platforme dominiraju video oglašavanjem, s 53% ulaganja koje ide na YouTube (u vlasništvu Googlea) i 29% na Facebook.¹² Ova koncentracija tržišne moći čini duopol "neizbježnim trgovinskim partnerom" i strukturnim "uskim grlom" za cijeli medijski i oglašivački ekosustav.¹³ Hrvatske novinske organizacije, ograničene jezičnim barijerama i specijaliziranim uredničkim misijama, nemaju financijske i tehničke resurse za izgradnju usporedivih podatkovnih infrastruktura ili postizanje mrežnih učinaka potrebnih za natjecanje.⁸ Rezultat je tržišni neuspjeh u kojem velika većina ekonomske vrijednosti stvorene internetskom pažnjom ne odlazi proizvođačima sadržaja, već distributerima.

::: {#tbl-ad-gap}
| Metrika                                                   | Vrijednost      | Izvor(i) |
|:----------------------------------------------------------|:----------------|:---------|
| Ukupna potrošnja na internetsko oglašavanje u Hrvatskoj    | €155 milijuna   | 12       |
| Zajednički udio društvenih medija i pretraživanja         | 51,9%           | 12       |
| Procijenjeni prihod duopola                               | €80,4 milijuna  | 12       |
| Ukupni prihod od pretplata na digitalne vijesti (2023.)    | €1,5 milijuna   | 14       |
| Bruto komercijalni prihod (sve web stranice s vijestima, 2015.) | ~€14,6 milijuna | 9        |

: Hrvatski digitalni oglašivački jaz (procjene za 2024.)
:::

*Napomena: Podatak o prihodima iz 2015. uključen je radi povijesne usporedbe kako bi se ilustrirala veličina nesrazmjera prihoda tijekom vremena.*

## 1.3. Potraga za održivošću

Suočeni sa sustavnim odljevom prihoda od oglašavanja, hrvatski medijski izdavači bili su prisiljeni istražiti alternativne strategije monetizacije, pri čemu su digitalne pretplate najistaknutije.⁷ Taj zaokret, međutim, započeo je relativno kasno, a većina izdavača uvela je **naplatne zidove** (*paywalls*) tek 2021. godine.¹⁴ Iako je rast broja pretplatnika značajan, s 30.500 u 2023. na 43.000 u prvom tromjesečju 2024., apsolutne brojke ostaju kritično niske.¹⁴ To predstavlja mali djelić ukupne publike internetskih vijesti; podaci pokazuju da samo prosječno **7,5% do 8%** hrvatskih potrošača digitalnih vijesti plaća za internetski sadržaj.¹⁰

Dominantni poslovni model koji se pojavio je "**freemium**", gdje je dio premium sadržaja zaključan iza naplatnog zida, dok većina ostaje besplatna.¹⁴ Ovaj hibridni pristup nije prijelazna strategija, već odražava temeljnu dilemu. Izdavači moraju većinu svog sadržaja držati besplatnim kako bi generirali veliki promet potreban za natjecanje za preostale oskudne dolare od oglašavanja, no upravo ta strategija obezvrjeđuje njihov proizvod u očima potrošača. Signalizirajući da većina novinarstva nije vrijedna plaćanja, freemium model se bori s njegovanjem široke kulture plaćanja, zarobljavajući izdavače u stanju ovisnosti o slomljenom tržištu oglašavanja od kojeg pokušavaju pobjeći. Pokušavaju služiti dvojici gospodara --- oglašivaču koji zahtijeva doseg i pretplatniku koji zahtijeva vrijednost --- i riskiraju da ne zadovolje nijednog.

Izravna ljudska posljedica ove krize prihoda je katastrofalan pad radnih uvjeta za hrvatske novinare. Medijski sektor je desetljeće ekonomskog pritiska devastiralo, a procjenjuje se da je od početka financijske krize posao izgubilo **800 novinara**.² Redakcije su se smanjile, a oni koji su ostali suočavaju se sa smanjenjem plaća, ponekad i do 50%, te porastom nesigurnih, slabo plaćenih honorarnih ugovora koji nemaju osnovnu socijalnu zaštitu.¹ Pandemija COVID-19 djelovala je kao snažan akcelerator ovih postojećih strukturnih problema, uzrokujući oštar pad prihoda za 70% elektroničkih medija i posebno teško pogađajući slobodne novinare.¹ Ova ekonomska nesigurnost posebno je izražena u lokalnim medijima, gdje je neodrživ financijski model doveo do pojave "**informativnih pustinja**" --- područja s lošom medijskom pokrivenošću koja se često preklapaju sa slabijim gospodarskim razvojem.¹⁰ Niske plaće u lokalnom novinarstvu, često između 500 i 700 eura mjesečno, stvaraju okruženje ekstremne ranjivosti.¹⁰

## 1.4. Ekonomski poticaj za senzacionalizam

Gore navedeni ekonomski pritisci nisu samo problem industrije; imaju izravan i korozivan učinak na kvalitetu i prirodu informacija koje čine hrvatsku javnu sferu. Postoji izravna uzročna veza između financijskog modela digitalnih medija i vrste sadržaja koji proizvode. U okruženju definiranom intenzivnom konkurencijom za pažnju publike i poslovnim modelom koji se pretežno oslanja na maksimiziranje klikova za programatsko oglašavanje, pojavljuje se snažan ekonomski poticaj za davanje prednosti jeftinom, velikoserijskom, senzacionalističkom sadržaju u odnosu na resursno intenzivnije oblike novinarstva.⁵

Ova ekonomska logika čini dubinsko novinarstvo od javnog interesa financijskim teretom. Istraživačko novinarstvo, koje zahtijeva značajno vrijeme, stručnost i pravni rizik za otkrivanje problema poput korupcije, organiziranog kriminala ili ratnih zločina, opisuje se kao "gotovo mrtvo" ili "sve rjeđe" u hrvatskom kontekstu.² Medijski izdavači, suočeni s golemim financijskim pritiskom, smatraju racionalnijim usredotočiti se na sadržaj koji se može jeftino proizvesti i koji će vjerojatno postati viralan, generirajući klikove potrebne za hvatanje djelića centa prihoda od oglasa.⁶ To dovodi do medijskog krajolika kojim dominira ono što se opisuje kao "površno, senzacionalističko, tabloidno i copy/paste" novinarstvo.⁵

Medijsko izvještavanje o migracijama služi kao jasan i zabrinjavajući primjer ove dinamike na djelu. Umjesto pružanja nijansiranog, činjeničnog izvještavanja, dokumentirano je da se mainstream mediji upuštaju u otvoreno senzacionalističko i zastrašujuće izvještavanje. Nacionalni dnevnik **Slobodna Dalmacija**, na primjer, nekritčki je prenio objavu s Facebooka jednog planinara koji je tvrdio da su migranti naoružani i teroriziraju lokalno stanovništvo, objavivši je pod naslovom osmišljenim da izazove uzbunu.¹⁸ Slično tome, televizijski kanal **RTL** promovirao je reportažu u kojoj su se njegovi novinari pridružili policiji na granici sa senzacionalističkim okvirom "lova na migrante".¹⁸ Ovakav tip izvještavanja, koji daje prednost emocionalnom utjecaju i kontroverzi nad činjeničnom točnošću, izravan je proizvod ekonomskih poticaja ekonomije temeljene na klikovima. To je u oštroj suprotnosti s ozbiljnim, istraživačkim radom o kršenjima ljudskih prava na granici, koji je sada gotovo isključivo domena malih, neovisnih, neprofitnih medija ili međunarodnih kuća koje nisu podložne istim komercijalnim pritiscima.¹⁸ Ova podjela medijskog krajolika --- s mainstream komercijalnim medijima usmjerenim prema senzacionalizmu i novinarstvom od javnog interesa potisnutim na margine --- izravna je posljedica političke ekonomije hrvatskog klika. Cijeli ovaj sustav stvorio je samopojačavajući ciklus propadanja: otimanje prihoda od oglašavanja od strane duopola gura medije u financijsku nesigurnost; ta nesigurnost potiče proizvodnju nekvalitetnog, senzacionalističkog sadržaja; rezultirajući pad kvalitete narušava povjerenje javnosti u medije; a to narušeno povjerenje smanjuje spremnost javnosti da plaća pretplate na vijesti, što zauzvrat pojačava ovisnost medija o slomljenom modelu oglašavanja, zatvarajući začarani krug.

---

# Odjeljak II: Ovisnost o prijeđenom putu i postojanost države

Snažni ekonomski pritisci globalne platformske ekonomije ne djeluju na hrvatski medijski sustav u vakuumu. Specifične ranjivosti i odgovori medija duboko su uvjetovani onim što povijesni institucionalisti nazivaju "**ovisnost o putanji**" (*path dependency*) --- idejom da odluke i događaji iz prošlosti ograničavaju i oblikuju mogućnosti u sadašnjosti.¹⁹ Suvremeni hrvatski medijski krajolik ne može se razumjeti bez istraživanja njegovih temelja, koji su postavljeni tijekom burne tranzicije iz državnog socijalizma 1990-ih. To razdoblje rata, izgradnje države i duboko manjkavog procesa privatizacije stvorilo je medijski sustav obilježen snažnim političkim paralelizmom, kulturom zarobljavanja medija i naslijeđem niskog povjerenja javnosti. Ovo povijesno naslijeđe djeluje kao kritični multiplikator ranjivosti, čineći medije daleko manje otpornima na ekonomske šokove digitalnog doba i komplicirajući napore za uspostavom istinskog digitalnog suvereniteta.

## 2.1. Privatizacija 1990-ih i politički paralelizam

Početna točka medijske tranzicije u Hrvatskoj bio je sustav državnih medija pod socijalizmom.²⁰ Pad tog sustava nije doveo do trenutnog nastanka liberalnog, neovisnog medijskog modela. Umjesto toga, 1990-e je definirao novi oblik političke kontrole pod ratnim predsjednikom Franjom Tuđmanom i njegovom vladajućom strankom Hrvatskom demokratskom zajednicom (HDZ). Nakon neovisnosti 1991. godine, HDZ je započeo sustavno preuzimanje državnih medija, najznačajnije nacionalne radiotelevizije, Hrvatske radiotelevizije (HRT).⁵ HRT je pretvoren iz javne ustanove u moćan instrument vladajuće stranke, korišten za promicanje vladine agende i, tijekom Domovinskog rata (1991.-1995.), za poticanje etničke mržnje i nacionalističke propagande.⁵ To je doba bilo obilježeno sveprisutnom državnom cenzurom i intenzivnim političkim pritiskom, što je ugušilo novinarsku autonomiju.²¹

Ovo političko preuzimanje odvijalo se paralelno sa širom privatizacijom hrvatskog gospodarstva, procesom koji su ekonomisti i promatrači naširoko kritizirali kao oblik "**kronističkog kapitalizma**".²³ Državna imovina, uključujući medijske kuće, često se prodavala po cijenama nižim od tržišnih novoj klasi vlasnika koji su bili privilegirani zbog svojih veza s vladajućom strankom.²³ Taj je proces bio namjerno netransparentan; publikacije su ponekad zatvarane iz političkih razloga pod izlikom nužnog gospodarskog restrukturiranja ili privatizacije.⁵ Ovaj mutan i visoko ispolitiziran proces privatizacije nije stvorio raznoliko i neovisno medijsko tržište. Umjesto toga, ukorijenio je vlasničke strukture koje su bile duboko isprepletene s političkim i gospodarskim elitama, uspostavljajući trajan obrazac onoga što je poznato kao "**politički paralelizam**" --- sustav u kojem se mediji usko povezuju s određenim političkim strankama ili frakcijama.²⁴ To naslijeđe 1990-ih postavilo je hrvatski medijski sustav na put definiran slabom profesionalizacijom novinarstva, snažnom ulogom države i duboko ukorijenjenim nepovjerenjem javnosti u neovisnost novinskih organizacija.²¹

## 2.2. Politika financiranja i vlasništva

Obrasci političkog utjecaja i zarobljavanja medija uspostavljeni 1990-ih pokazali su se iznimno postojanima, nastavljajući oblikovati medijski krajolik desetljećima kasnije. Otvorena državna cenzura zamijenjena je suptilnijim, ali jednako učinkovitim mehanizmima kontrole. Politički pritisak ostaje definirajuća značajka hrvatskog medijskog okruženja, potkopavajući novinarsku slobodu i potičući klimu cenzure i autocenzure.¹⁶ To je vidljivo u kontinuiranom političkom uplitanju u upravljanje i uređivačku politiku javnog servisa HRT-a, koji je kritiziran zbog favoriziranja vladajuće stranke pa je čak tužio i vlastite kritične novinare.³ Pritisak nije ograničen na javne medije; dokumentirano je da visoki političari, uključujući premijera, vrše izravan pritisak na velike komercijalne televizijske kanale.¹

Jedna od primarnih poluga suvremenog zarobljavanja medija je netransparentna dodjela javnih sredstava. Lokalni mediji, koji su već u nesigurnom financijskom položaju zbog tržišne dinamike opisane u Odjeljku I, često su uvelike ovisni o financijskoj potpori lokalnih i državnih vlasti.¹⁰ Ta se ovisnost sustavno iskorištava kao alat političke kontrole. Sredstva se često dodjeljuju na netransparentan i diskrecijski način, nagrađujući medije koji pružaju povoljno izvještavanje i kažnjavajući one koji su kritični prema vlastima.³ Ova praksa korištenja državnog oglašavanja i subvencija za manipuliranje medijima ključan je instrument kontrole.¹⁶

Ovaj politički utjecaj dodatno je otežan postojanim nedostatkom transparentnosti u vlasništvu medija. Iako hrvatski zakon zahtijeva objavu vlasničkih struktura, pravna definicija "stvarnih vlasnika" je slaba, što omogućuje da pravi izvori financijskog i političkog utjecaja ostanu skriveni.³ Ta netransparentnost, u kombinaciji s visokom koncentracijom vlasništva u ključnim sektorima poput tržišta regionalnog tiska, izaziva značajnu zabrinutost za medijski pluralizam i uredničku neovisnost.³ Cijeli ovaj sustav --- rođen iz ispolitizirane privatizacije 1990-ih --- stvorio je strukturno ranjivo medijsko okruženje. Povijesni put doveo je do sustava s dubokim "**deficitom povjerenja**". U nedostatku snažnog temelja povjerenja javnosti i tradicije žestoke neovisnosti, hrvatski su mediji ušli u digitalno doba bez društvenog i financijskog kapitala --- konkretno, velike i lojalne baze pretplatnika spremnih platiti za pouzdano novinarstvo --- potrebnog da izdrže ekonomski šok koji je donio duopol platformi. Već postojeći deficit povjerenja, izravna posljedica njegove povijesne putanje, učinio je zaokret prema modelu financiranom od strane čitatelja izuzetno teškim, čime se multiplicirala ranjivost medija na propadajuće tržište oglašavanja.

## 2.3. Potraga za digitalnim suverenitetom

Posljednjih godina, hrvatska javna sfera, kao i ona svih država članica EU, postala je mjesto napetosti između de facto upravljanja tehnoloških tvrtki sa sjedištem u Kaliforniji i obnovljenih napora nacionalnih i europskih regulatora da ponovno uspostave kontrolu. Ta borba je u središtu suvremene rasprave o "**digitalnom suverenitetu**" --- sposobnosti države ili bloka da upravlja vlastitim digitalnim prostorom u skladu s vlastitim zakonima i vrijednostima.²⁶ Glavni instrumenti u tom naporu su ključni zakonodavni paketi EU: Opća uredba o zaštiti podataka (GDPR) i, odnedavno, Akt o digitalnim uslugama (DSA).

DSA, koji je postao u potpunosti primjenjiv u veljači 2024., predstavlja najznačajniji pokušaj regulacije digitalnog okruženja do danas.²⁷ Cilj mu je stvoriti sigurniji i transparentniji internetski prostor nametanjem sveobuhvatnog skupa novih obveza digitalnim posrednicima, posebice velikim internetskim platformama.²⁹ Ta pravila pokrivaju moderiranje sadržaja, prava korisnika, transparentnost u oglašavanju i algoritamskim sustavima preporuka te odgovornost za širenje nezakonitog sadržaja.²⁸ Hrvatska je službeno provela ovu EU uredbu nacionalnim zakonom koji je stupio na snagu u travnju 2025.³⁰ Zakon imenuje niz nadležnih nacionalnih tijela odgovornih za provedbu, uključujući Hrvatsku regulatornu agenciju za mrežne djelatnosti (HAKOM), koja djeluje kao središnji koordinator za digitalne usluge, kao i Državno odvjetništvo, Agenciju za zaštitu osobnih podataka i druge, ovisno o prirodi povrede. Uspostavlja mehanizme za pritužbe korisnika i propisuje znatne novčane kazne za nepoštivanje.³⁰

Međutim, ovaj poticaj za digitalnim suverenitetom suočava se sa značajnim izazovima, stvarajući složenu borbu na dva fronta. Na vanjskom frontu, propisi EU u izravnom su sukobu s pravnim okvirima drugih jurisdikcija, ponajviše s američkim Zakonom o pojašnjavanju zakonite prekomorske upotrebe podataka (CLOUD Act). CLOUD Act omogućuje američkim tijelima za provedbu zakona da prisile tvrtke sa sjedištem u SAD-u da dostave podatke pohranjene bilo gdje u svijetu, uključujući i unutar EU, čime se zaobilaze i potkopavaju načela zaštite podataka sadržana u GDPR-u.³¹ To stvara "paradoks suvereniteta", gdje su podaci pohranjeni na tlu EU od strane američkih tvrtki i dalje podložni američkom zakonu, što dovodi u pitanje samu ideju europskog suvereniteta podataka.

Na unutarnjem frontu, učinkovitost propisa poput DSA-a u potpunosti ovisi o neovisnosti i integritetu nacionalnih tijela zaduženih za njihovu provedbu. Upravo te državne institucije u Hrvatskoj koje su sada imenovane kao "nadležna tijela" za reguliranje internetskog sadržaja iste su one koje su bile upletene u dugogodišnji sustav političkog pritiska i netransparentnog financiranja medija. To stvara značajan rizik da bi regulatorni alat osmišljen da pozove na odgovornost globalne platforme mogli prisvojiti domaći politički akteri i koristiti ga kao još jednu polugu za političku kontrolu nad internetskim govorom. Borba za istinski suveren i demokratski digitalni prostor u Hrvatskoj stoga nije samo reguliranje Googlea i Facebooka; jednako je važno osigurati neovisnost i odgovornost samih domaćih regulatora.

---

# Odjeljak III: Algoritamska arhitektura javnog diskursa

Nakon što smo ispitali ekonomske i političko-povijesne kontekste, analiza se sada mora okrenuti tehnološkim sustavima koji posreduju u hrvatskoj javnoj sferi. Dominantne platforme, prvenstveno Facebook i Google, nisu neutralne infrastrukture. Njihovim uslugama upravljaju složeni, netransparentni algoritmi čiji su dizajni kodirani sa specifičnim komercijalnim ciljevima. Ovi algoritamski sustavi aktivno oblikuju javni diskurs određujući koje su informacije vidljive, koji se sadržaj pojačava i koji se oblici komunikacije nagrađuju. Ovaj odjeljak će tvrditi da sama arhitektura ovih platformi stvara snažne poticaje koji mogu degradirati kvalitetu javne rasprave, pojačati polarizaciju i stvoriti nova bojišta za političku manipulaciju.

## 3.1. Facebookov mehanizam angažmana i uspon negativnosti

Facebook je jedan od najpopularnijih i najutjecajnijih izvora vijesti i informacija u Hrvatskoj, a većina građana koristi platformu kako bi ostala informirana.¹¹ Međutim, njegova uloga seže daleko izvan uloge jednostavnog kanala distribucije. Sadržaj koji korisnici vide u svom News Feedu nije kronološki ili neutralan prikaz onoga što su njihove veze objavile; to je visoko kurirana stvarnost, konstruirana algoritmom osmišljenim da maksimizira jednu primarnu metriku: angažman korisnika. Ključan trenutak u evoluciji te logike bio je Facebookov pomak 2018. godine prema davanju prioriteta "**Značajnim društvenim interakcijama**" (MSI).

Navedena namjera iza ažuriranja MSI bila je poticanje osobnijih veza davanjem prioriteta sadržaju koji je poticao razgovore među korisnicima. U praksi, algoritam je počeo snažno favorizirati sadržaj koji je generirao velik broj interakcija --- posebno komentara, dijeljenja i emocionalnih reakcija visokog uzbuđenja (poput "ljutitog" emojija). Iako možda nenamjerno, značajna posljedica ove arhitektonske promjene bila je sustavna amplifikacija bijesa, sukoba i razdornog političkog sadržaja.³³ Opsežna istraživanja o političkoj komunikaciji na Facebooku, uključujući tijekom izbora za Europski parlament, pokazala su da objave osmišljene da izazovu negativne emocije, objave koje koriste dramatizaciju i senzacionalizam te objave koje se upuštaju u negativne kampanje dosljedno postižu više razine angažmana korisnika u obliku lajkova, dijeljenja i komentara.³⁴

Ova algoritamska logika stvara snažan strukturni poticaj za političke aktere. U hrvatskom političkom kontekstu, gdje su stranke i političari često kritizirani zbog korištenja Facebooka kao jednosmjernog alata za samopromociju, a ne za istinski dijalog s građanima ³⁵, algoritam vođen MSI-jem nagrađuje drugačiji, korozivniji stil komunikacije. Kako bi postigli vidljivost i doseg, politički akteri implicitno se potiču da usvoje negativnije, populističke i emocionalno nabijene poruke. Ova dinamika pridonosi formiranju "**disonantne javne sfere**", gdje racionalno argumentiranje biva zamijenjeno afektivnom polarizacijom.³⁴ To otkriva kritičko usklađivanje poticaja: komercijalna potreba platforme za angažmanom savršeno je zadovoljena vrstom poruka visokog uzbuđenja i sukoba u kojima se specijaliziraju populistički i disruptivni politički akteri. Algoritam, u potrazi za čisto komercijalnim ciljem, sustavno nagrađuje i pojačava upravo onu vrstu političke komunikacije koja je najštetnija za deliberativan, činjenični demokratski diskurs, stvarajući plodno tlo za polarizaciju i širenje dezinformacija.³³

## 3.2.+ SEO kao nevidljivo političko bojište

Dok kontroverze oko Facebookovog algoritma često zaokupljaju javnu pažnju, moć koju ima Googleova tražilica vjerojatno je temeljnija i djeluje suptilnije. S golemim udjelom od **96%** na tržištu pretraživanja u Hrvatskoj, Google je neosporan ulaz u informacije za gotovo cjelokupno internetsko stanovništvo.³⁶ Ovaj monopol stvara snažan "**efekt lijevka**": za veliku većinu korisničkih upita, nekolicina rezultata prikazanih na prvoj stranici predstavlja učinkovitu i konačnu stvarnost dostupnog znanja o toj temi.

Ova dinamika pretvara **optimizaciju za tražilice (SEO)** iz puke marketinške taktike u kritičan oblik infrastrukturne moći. Sposobnost pojavljivanja na vrhu Googleovih rezultata pretraživanja je bitka za javnu vidljivost, narativnu kontrolu i percipirani autoritet. Temeljni stupovi uspješne SEO strategije u Hrvatskoj --- stvaranje kulturno i jezično nijansiranog sadržaja, izgradnja mreže povratnih veza s uglednih lokalnih domena (poput velikih novinskih portala) i osiguravanje besprijekornih tehničkih i mobilnih performansi --- jednako se primjenjuju na tvrtku koja prodaje proizvod i na političkog aktera koji promiče ideologiju.³⁶

Političke implikacije ovoga su duboke. Iako dostavljeno istraživanje ne sadrži specifične studije slučaja hrvatskih političkih stranaka koje eksplicitno detaljiziraju svoje SEO strategije, potencijal za manipulaciju je ogroman. Moć pretraživanja leži u njegovoj percipiranoj neutralnosti. Za razliku od feeda na društvenim mrežama, za koji se razumije da je personaliziran, rezultat Google pretraživanja korisnici često vide kao objektivan, autoritativan odgovor. Akteri koji uspješno ovladaju SEO-om mogu stoga uokviriti javno razumijevanje problema prije nego što rasprava i započne. Mogu osigurati da njihove web stranice i narativi budu prvi i najvidljiviji izvori s kojima se građanin susreće prilikom traženja informacija, čime učinkovito postavljaju agendu i marginaliziraju suprotstavljena stajališta. To je dublji i manje istražen oblik moći od borbe za viralnost pojedinačnih objava na društvenim mrežama. To je moć oblikovanja samog informacijskog ekosustava, a budući da je zaogrnuta tehničkim i naizgled objektivnim procesom "rangiranja", često izmiče političkom nadzoru koji se primjenjuje na vidljivije platforme. Uspon generativne umjetne inteligencije dodaje opasnu novu dimenziju ovome, omogućujući brzo stvaranje ogromnih količina uvjerljivog, ali lažnog ili obmanjujućeg sadržaja koji se može koristiti za preplavljivanje rezultata pretraživanja i manipuliranje javnim mnijenjem.³⁷

## 3.3. Manipulacija u praksi: Dezinformacije, botovi i netransparentni oglasi

Teorijski potencijal za manipulaciju unutar ove algoritamske arhitekture ostvaruje se u praksi kroz niz taktika koje su dokumentirale hrvatske organizacije civilnog društva i istraživači. Hrvatska je dom stabilnog dezinformacijskog ekosustava koji se sastoji od mreže krajnje desnih političkih aktera, marginalnih medija i anonimnih profila na društvenim mrežama.³⁷ Ova mreža aktivno širi dezinformacije o politički nabijenim temama kao što su migracije, klimatske promjene, rodna ravnopravnost i javno zdravstvo, često koristeći iste aktere i kanale koji su bili istaknuti tijekom pandemije COVID-19.³⁷

Rad na praćenju izbora hrvatske organizacije civilnog društva **Gong** pruža ključne, konkretne studije slučaja ovih manipulativnih praksi na djelu. Njihova analiza nedavnih predsjedničkih i parlamentarnih izbora otkrila je brojne primjere sofisticirane digitalne manipulacije.⁴¹ To uključuje koordinirane, višestruke klevetničke kampanje usmjerene na određene kandidate; korištenje lažnih profila i automatiziranih "bot" računa (posebno na TikToku) za stvaranje umjetnog dojma narodne podrške ili protivljenja; i strateško širenje sumnjivih ili pristranih istraživanja neposredno prije službenog razdoblja izborne šutnje kako bi se utjecalo na birače u zadnji čas.⁴¹

Nadalje, Gong je opsežno dokumentirao sveprisutan problem netransparentnog političkog oglašavanja.⁴² Tijekom izbornih razdoblja, brojni kandidati i stranke prikazivali su internetske oglase bez da su ih ispravno označili kao političke. Umjesto toga, koriste obmanjujuće kategorije poput "poslovanje" ili "zdravlje" kako bi prikrili svoje kampanjske aktivnosti. Ova praksa služi za prikrivanje stvarnih razmjera troškova kampanje i, u nekim slučajevima, omogućuje financiranje kampanje iz ilegalnih izvora, kao što su privatne udruge.⁴² Ovi nalazi ističu dvostruki neuspjeh: neadekvatnost samoregulacijskih mehanizama samih platformi, koji ne uspijevaju dosljedno identificirati i označiti politički sadržaj, i nedjelovanje nadležnih državnih tijela odgovornih za nadzor financiranja kampanja, koja nisu djelovala čak ni kada su im predočeni jasni dokazi o kršenjima.⁴² Složenost ovog problema naglašena je činjenicom da su velike platforme poput Googlea na kraju odlučile u potpunosti se povući iz političkog oglašavanja u EU, radije nego da riskiraju neusklađenost s strogim novim pravilima Uredbe o transparentnosti i ciljanju u političkom oglašavanju (TTPA), čime su zapravo priznale poteškoće u adekvatnom nadzoru vlastitih sustava.⁴²

---

# Zaključak i preporuke

Stanje digitalnih medija u Hrvatskoj proizvod je sustavnog stanja, složene i duboko ukorijenjene isprepletenosti globalne ekonomije, nacionalne političke povijesti i tehnološke arhitekture. Analiza je pokazala da ekonomska nesigurnost novinarstva, pad povjerenja javnosti i prevalencija senzacionalističkog i politički manipuliranog sadržaja nisu izolirani problemi, već simptomi sustava pod golemim, isprepletenim pritiskom. Moć globalnog oglašivačkog duopola koja iscrpljuje prihode napada medijski sektor koji je postao jedinstveno ranjiv zbog povijesne ovisnosti o putanji političkog zarobljavanja i niskog povjerenja javnosti. Cijela se ta dinamika zatim pojačava i ubrzava logikom algoritama vođenih angažmanom koji nagrađuju bijes i stvaraju nova, često nevidljiva, bojišta za narativnu kontrolu. Rješavanje ove višestruke krize zahtijeva nadići pojednostavljena rješenja i usvojiti okvir usmjeren na izgradnju sustavne otpornosti. Sljedeće preporuke upućene su ključnim dionicima i osmišljene su da interveniraju na različitim točkama unutar ovog složenog sustava.

## Provedive preporuke

### Za hrvatske donositelje politika i regulatore:

* **Ojačati i jamčiti neovisnost koordinatora za DSA (HAKOM):** Uspješna provedba Akta o digitalnim uslugama je ključna, ali njezin potencijal može biti potkopan ako su provedbena tijela podložna političkom utjecaju. Nužno je provesti snažne pravne i proceduralne zaštitne mjere kako bi se osiguralo da su HAKOM i druga imenovana nadležna tijela u potpunosti izolirana od političkih pritisaka koji su povijesno karakterizirali hrvatsku medijsku regulaciju. To uključuje transparentne postupke imenovanja, sigurno financiranje neovisno o godišnjim političkim proračunima i snažan parlamentarni nadzor.
* **Radikalna transparentnost u javnom financiranju:** Korištenje državnog i lokalnog financiranja medija kao alata za politički klijentelizam mora prestati. Trenutni sustav netransparentnih, diskrecijskih potpora treba zamijeniti transparentnim, formulativnim modelom kojim upravlja neovisno tijelo. Sredstva bi se trebala dodjeljivati za podršku novinarstvu od javnog interesa na temelju jasnih, objektivnih i javno dostupnih kriterija, kao što su broj zaposlenih novinara, predanost etičkim kodeksima i proizvodnja originalnog istraživačkog ili lokalnog sadržaja. To bi prekinulo toksičnu vezu između javnog novca i političke lojalnosti.
* **Ulagati u medijsku pismenost na nacionalnoj razini:** Otporna demokracija zahtijeva otporno građanstvo. Hrvatska bi trebala pokrenuti sveobuhvatan, dugoročan nacionalni program medijske i digitalne pismenosti. Taj program mora biti integriran u formalni obrazovni kurikulum od rane dobi i dostupan široj javnosti. Cilj je opremiti građane vještinama kritičkog razmišljanja potrebnim za prepoznavanje dezinformacija, razumijevanje algoritamskog utjecaja i procjenu vjerodostojnosti izvora u zagađenom informacijskom okruženju.

### Za hrvatske medijske organizacije i novinare:

* **Surađivati kako bi se suprotstavili duopolu:** Pojedinačne medijske kuće su premale da bi učinkovito pregovarale s globalnim platformama. Hrvatski izdavači trebali bi istražiti formiranje saveza ili konzorcija kako bi kolektivno pregovarali s Googleom i Metom za pravednu naknadu za korištenje njihovog sadržaja, po uzoru na zakonodavne i industrijske modele u zemljama poput Australije i Kanade. Nadalje, takvi konzorciji mogli bi stvoriti zajedničku tehnološku infrastrukturu za analitiku podataka i upravljanje pretplatama, smanjujući pojedinačne troškove i poboljšavajući njihovu sposobnost natjecanja.
* **Udvostručiti napore na jedinstvenoj vrijednosti:** U informacijskom okruženju zasićenom nekvalitetnim, algoritamski pojačanim sadržajem, jedina održiva konkurentska prednost profesionalnog novinarstva je kvaliteta. Medijske kuće moraju usmjeriti svoja ograničena sredstva na proizvodnju novinarstva koje platforme i umjetna inteligencija ne mogu replicirati: duboko istražene, visokokvalitetne lokalne vijesti koje služe specifičnim potrebama zajednice i rigorozan istraživački rad koji poziva moćne na odgovornost. To je sadržaj koji gradi povjerenje, potiče lojalnost i na kraju opravdava pretplatu.
* **Prihvatiti "novinarstvo angažirano s publikom":** Kako bi ponovno izgradili povjerenje i njegovali publiku koja plaća, mediji se moraju prebaciti s modela emitiranja "odozgo prema dolje" na onaj koji zajednicu vidi kao partnera. To uključuje aktivno uključivanje publike u proces izvještavanja, transparentnost u pogledu uredničkih odluka i financiranja te stvaranje foruma za konstruktivan građanski dijalog. Publika koja se osjeća kao dionik u misiji medijske kuće daleko je vjerojatnije da će postati lojalan, plaćajući podupiratelj.

### Za organizacije civilnog društva (OCD) i zagovornike digitalnih prava:

* **Održavati nadzor nad platformama i regulatorima:** Rad nadzornih organizacija poput Gonga ključniji je nego ikad. OCD-i moraju nastaviti i proširiti svoje praćenje usklađenosti platformi s DSA-om i drugim propisima. Ključno je da se taj nadzor usmjeri i na sama nacionalna regulatorna tijela, pozivajući ih na odgovornost i osiguravajući da njihove nove ovlasti ne budu prisvojene u političke svrhe, čime se vodi "rat na dva fronta" za digitalni suverenitet.
* **Razvijati alate za algoritamsku odgovornost namijenjene javnosti:** Nadovezujući se na obećavajuće inicijative poput javnih registara upotrebe umjetne inteligencije u javnom sektoru ⁴⁴, OCD-i bi se trebali usredotočiti na razvoj alata, izvješća i vizualizacija podataka koji utjecaj algoritama --- kako na feedovima društvenih medija tako i u rezultatima pretraživanja --- čine vidljivim i razumljivim široj javnosti, novinarima i donositeljima politika. Demistificiranje ovih "crnih kutija" ključan je korak prema javnoj odgovornosti.
* **Zalagati se za zaštitu novinarskih i digitalnih prava:** Pravna i fizička sigurnost novinara preduvjet je za funkcioniranje demokracije. OCD-i moraju nastaviti voditi borbu protiv **Strateških tužbi protiv javnog sudjelovanja (SLAPP)** kroz zagovaranje i strateške parnice.²⁵ Također moraju ostati budni u osiguravanju da se provedba novih digitalnih propisa, iako nužna, provodi na način koji u potpunosti poštuje i štiti temeljna prava građana na privatnost i slobodu izražavanja na internetu.