---
title: "02-podatci"
format: html
editor: visual
---

---
title: "Digitalni ekosustav"
author: "Luka Sikic"
date: "2025-10-07"
format: 
  html:
    toc: true
    toc-location: left
    theme: cosmo
editor: visual
---

Digitalni medijski ekosustav u četveromilijunskoj Hrvatskoj predstavlja kompleksno polje obilježeno dubokim strukturnim paradoksima. Na prvi pogled, brojke ukazuju na zrelo i rastuće tržište; prihod od digitalnog oglašavanja u 2024. godini dosegnuo je 155 milijuna eura, uz snažan međugodišnji rast od 16,4%, čime se ukupno oglašivačko tržište vratilo na razinu od 2% BDP-a, posljednji put viđenu pred globalnu krizu 2007. godine. Ipak, ispod te površine krije se složena stvarnost definirana inozemnom dominacijom u vlasničkoj strukturi, sveprisutnim mobilnim pristupom koji generira čak 81% potrošnje na digitalno oglašavanje te izrazito proturječnim ponašanjem potrošača. Unatoč visokoj internetskoj penetraciji koja obuhvaća 84,4% populacije, istovremeno se bilježi alarmantno visoka stopa izbjegavanja vijesti od 61% te jedna od globalno najnižih stopa spremnosti na plaćanje online sadržaja, koja iznosi svega 6%. Ovaj rascjep između dosega i monetizacije događa se u kontekstu države koja, s jedne strane, u digitalizaciji malih i srednjih poduzeća (32% ih prodaje online naspram EU prosjeka od 20%) nadmašuje europski prosjek, dok je, s druge strane, prema ukupnom indeksu digitalnoga gospodarstva i društva (DESI) pozicionirana na skromnom 21. mjestu od 27 članica Europske unije.

# Digitalni informativni mediji: Između krize povjerenja i neodrživih poslovnih modela

Struktura hrvatskih digitalnih informativnih medija otkriva dubok raskorak između zrelog dosega i ekonomske krhkosti. Analiza prometa pokazuje ekstremnu tržišnu koncentraciju, gdje tri vodeća portala suvereno dominiraju. Index.hr predvodi s 54,5 milijuna mjesečnih posjeta, a slijede ga Jutarnji.hr s 53,5 milijuna i 24sata.hr s 25,8 milijuna. Činjenica da samo tri medijske kuće generiraju preko 130 milijuna posjeta u zemlji s 3,86 milijuna stanovnika ne upućuje samo na intenzivnu i opetovanu konzumaciju sadržaja od strane istih korisnika, već i na sužen medijski prostor. Dominacija mobilnih uređaja pritom je postala gotovo apsolutna, što ilustrira podatak da čak 91,2% prometa portala Jutarnji.hr dolazi s mobitela.

Ključ za razumijevanje dinamike tržišta leži u njegovoj vlasničkoj strukturi. Austrijska Styria Media Group, vlasnik 24sata i Večernjeg lista, kontrolira između 50 i 60 posto naklade tiskanih medija, s golemim utjecajem i na digitalni prostor. S druge strane, najveća grupacija u domaćem vlasništvu, Hanza Media, iako je u 2023. ostvarila ukupan prihod od 36,78 milijuna eura, od digitalnih je operacija prihodovala svega 7,59 milijuna eura, što čini tržišni udio od samo 3,41%. Komercijalnim televizijskim prostorom, koji je i dalje ključan za informiranje građana, upravljaju United Group (vlasnik Nove TV, najgledanije komercijalne televizije od 2010.) i češki Central European Media Enterprises (vlasnik RTL-a). Posljedično, cjelokupnom distribucijom vijesti u Hrvatskoj upravljaju tri velike grupacije, od kojih su dvije u stranom vlasništvu.

Poslovni modeli ostaju tvrdoglavo ovisni o oglašavanju, primarno zbog fenomena koji se može opisati kao izvanredan otpor hrvatskih potrošača prema plaćanju informativnog sadržaja. Sa svega 6% građana koji plaćaju online vijesti, Hrvatska se nalazi na samom dnu globalnih ljestvica Reutersovog Instituta, daleko ispod prosjeka od 18% zabilježenog u dvadeset anketiranih zemalja. Iako je tržište online oglašavanja dosegnulo 155 milijuna eura, tradicionalna televizija i dalje privlači najveći dio marketinškog kolača, otprilike 125 milijuna eura, što čini oko 47% ukupne potrošnje. Ta surova financijska računica – zanemariv prihod od pretplata i oglašivačko tržište dimenzionirano za malu populaciju – ostavlja digitalno novinarstvo na izrazito tankim marginama. Takvo okruženje sustavno destimulira zahtjevno istraživačko novinarstvo i potiče raširenu praksu prenošenja i recikliranja sadržaja.

Analiza kvalitete tog sadržaja otkriva duboke sustavne probleme. Studije iz 2022. godine pokazale su da 30% članaka nema jasno navedenog autora, dok 14% ne navodi nikakve izvore. Alarmantan je podatak da se čak 82,4% članaka oslanja isključivo na službene izvore ili prenošenje vijesti iz drugih medija, umjesto na originalno izvještavanje. Od preko 170 registriranih news portala u Hrvatskoj, mnogi funkcioniraju kao puki preslikači sadržaja s vodećih medija ili agencije HINA, koja dnevno proizvede oko 60 ekonomskih izvještaja i 600 fotografija koje služe kao primarni materijal za čitav ekosustav.

Sve to izravno se odražava na povjerenje javnosti, koje je na zabrinjavajuće niskoj razini od samo 36%, što je značajan pad od 9 postotnih bodova u odnosu na ranija mjerenja. Još je alarmantniji podatak da 61% Hrvata povremeno ili često aktivno izbjegava vijesti, što Hrvatsku, uz Bugarsku (63%), Tursku i Grčku, svrstava u sam svjetski vrh po toj negativnoj metrici. U tom kontekstu razvija se i paradoks da komercijalne televizije, Nova TV i RTL, uživaju veće povjerenje od javnog servisa HRT-a, dok se politički profilirani portali poput Index.hr i Dnevno.hr percipiraju kao najmanje vjerodostojni. Stvoren je začarani krug: nisko povjerenje potiče izbjegavanje vijesti, što smanjuje doseg i interes oglašivača, što pak prisiljava medije na rezanje troškova, a to neizbježno vodi daljnjem padu kvalitete i, posljedično, još nižem povjerenju. Na sve ove probleme nadovezuje se i okruženje pravne nesigurnosti; u 2024. godini bila su aktivna 752 sudska postupka protiv novinara. Iako je taj broj manji u odnosu na 945 tužbi iz 2023., on i dalje predstavlja golem teret, pogotovo jer je analiza 1.333 tužbe podnesene između 2016. i 2023. pokazala da ih čak 41% ima karakteristike SLAPP tužbi (strateških tužbi protiv javnog sudjelovanja), čiji je cilj zastrašivanje i iscrpljivanje novinara, uz prosječno trajanje procesa od četiri godine. Tome treba dodati i netransparentnu potrošnju na državno oglašavanje, koja, iako službeno dokumentirana na 351.437 eura u 2023., stvara sumnju u postojanje skrivenih financijskih tokova i potencijalnu medijsku zavisnost.

# Društveni mediji

Hrvatski krajolik društvenih medija pokazuje znakove zrelog tržišta s 2,79 milijuna aktivnih korisnika, što predstavlja penetraciju od 69,8% populacije i pozicionira zemlju usporedivo s regionalnim susjedima poput Srbije (70,3%) i Bosne i Hercegovine (64%). Ekosustav je pritom savršeno rodno uravnotežen, no preferencije korisnika značajno se razlikuju od platforme do platforme.

YouTube funkcionira kao univerzalna platforma, s dosegom koji je praktički ekvivalentan ukupnom broju korisnika društvenih medija. Facebook, unatoč globalnim narativima o njegovom padu, u Hrvatskoj ostaje neprikosnoveno središte društvene interakcije. S 2,57 milijuna korisnika, on generira nevjerojatnih 80,9% svih posjeta društvenim mrežama, prema podacima StatCountera, što pokazuje njegovu duboku ukorijenjenost u digitalne navike građana. Instagram se etablirao kao primarna vizualna platforma s 1,54 milijuna korisnika, gdje prevladavaju žene (56,1%), a dominira dobna skupina od 25 do 34 godine koja čini 32% korisnika. TikTok predstavlja najdinamičniji i najbrže rastući segment, s 1,05 milijuna korisnika starijih od 18 godina i uravnoteženijom rodnom strukturom (52,5% žena). Njegova putanja je strma; identificirano je 62.746 aktivnih hrvatskih kreatora sadržaja, a predviđa se da će mu se udio u oglašavanju učetverostručiti u 2025. godini, s dva na osam posto. U profesionalnoj sferi, LinkedIn bilježi snažan rast od 18,3% i okuplja 930.000 članova, gdje također dominira dobna skupina od 25-34 godine s 36,5% udjela. U potpunoj suprotnosti, Twitter/X doživljava dramatičan pad od 35,4%, sveden na svega 419.000 korisnika i s izrazitom dominacijom muškaraca (65,3%).

Korisnici u Hrvatskoj provode u prosjeku 2 sata i 21 minutu dnevno na društvenim medijima, što je neznatno iznad europskog prosjeka. Intenzitet korištenja pojedinih platformi prati globalne trendove, s TikTokom na vrhu. Demografski obrasci otkrivaju najoštriji društveni rascjep – generacijski jaz. Dok 97% mladih u dobi od 16 do 29 godina svakodnevno koristi internet, a 84% ih je na društvenim medijima, angažman drastično opada nakon 50. godine života. Razlika od 21 postotnog boda u korištenju interneta između mladih i starije populacije najviša je u cijeloj Europskoj uniji. S obzirom na medijalnu dob stanovništva od 44,3 godine i činjenicu da 22,9% populacije ima preko 65 godina, demografija predstavlja ključnu strukturnu prepreku daljnjem eksponencijalnom rastu digitalnih platformi.

Paralelno s time, influencerski ekosustav brzo se profesionalizirao, dosegnuvši tržišnu vrijednost od 18,4 milijuna dolara u 2024., s projekcijom rasta na 25,7 milijuna do 2028. uz godišnju stopu od 8,74%. Registrirano je 3.211 influencera na Instagramu i 15.870 na TikToku, a njihove stope angažmana značajno su iznad globalnih prosjeka – primjerice, influenceri u kategoriji zabave postižu 7,30%, putovanja 6,46%, a fitnessa 5,55%. Tržištem dominiraju mikro i nano-influenceri (s 1.000 do 10.000 pratitelja), koji čine 75,9% svih influencera na Instagramu i postižu superiorne rezultate, što ih čini isplativima za oglašivače. Taj trend izravno potiče ubrzanje društvene trgovine, budući da preko 70% Hrvata kupuje online, a 62% svih e-commerce transakcija odvija se putem pametnih telefona. Ukupno tržište e-trgovine, procijenjeno na 1,05 milijardi dolara u 2025., trebalo bi dosegnuti 2,03 milijarde do 2030. godine, podržano infrastrukturom poput više od 2.000 paketomata postavljenih od 2021. godine.

# Streaming, oglašavanje i infrastruktura: Slika neujednačenog razvoja

Hrvatsko tržište streaminga i dalje je u ranoj fazi rasta. Segment pretplatničkog videa na zahtjev (SVoD) u 2024. godini dosegnuo je vrijednost od 16,18 milijuna dolara uz penetraciju od samo 11%, s projekcijom rasta na 19,58 milijuna do 2027. i penetraciju od 12,2%, što ukazuje na značajan prostor za rast u usporedbi sa zapadnoeuropskim tržištima gdje se penetracija kreće između 15 i 20 posto. Glazbeni streaming, vrijedan 8,48 milijuna dolara, raste još brže, nakon što je Hrvatska 2022. bila drugo najbrže rastuće tržište na svijetu s 58% godišnjeg rasta.

Tržištem dominiraju globalni divovi. Netflix, čija penetracija ostaje ispod 3,5% populacije, nudi pakete od 4,99 do 9,99 eura, nakon što je u veljači 2023. snizio cijene, ispravljajući situaciju u kojoj su hrvatski pretplatnici plaćali 53% više od američkih za usporedivu uslugu. HBO Max (sada Max) lansiran je 8. ožujka 2022., a Disney+ 14. lipnja 2022., dok je Amazon Prime Video dostupan od 2016., ali s ograničenom lokalnom bibliotekom. Znakovita je, međutim, činjenica da Apple TV+ još uvijek nije dostupan u Hrvatskoj, za razliku od susjedne Slovenije, što signalizira da globalne platforme procjenjuju hrvatsko tržište kao nedovoljno veliko za trenutno pokretanje operacija. Spotify je stigao u srpnju 2020. i postao vodeća glazbena platforma.

Domaći igrači, poput MAXtv-a (Hrvatski Telekom) koji je još 2006. bio prva IPTV platforma u Deutsche Telekom grupi, i EON-a (A1/United Group) s više od 19.000 naslova na zahtjev, svoju konkurentsku prednost grade primarno kroz telekom pakete. Tu je i nišna platforma Svevid, fokusirana na domaću kinematografiju. Zakon o elektroničkim medijima propisuje obvezu da 10% programa potječe od neovisnih producenata i da se 2% prihoda ulaže u hrvatska audiovizualna djela, no unatoč tome, lokalna produkcija je skromna. Iako 57% Hrvata i dalje navodi televiziju kao primarni izvor informacija, konzumacija podcasta dosegnula je 37% na mjesečnoj razini. U sjeni videa, gaming industrija tiho stvara ekosustav vrijedan 95 milijuna dolara u 2024., s projekcijom rasta na 113 milijuna do 2027., pri čemu mobilne igre čine 22,51 milijun dolara.

Digitalno oglašavanje, vrijedno 155 milijuna eura, raste po dvoznamenkastim stopama i predviđa se da će dosegnuti 336,9 milijuna dolara do 2028. Njegova je struktura definirana dvjema dominantnim silama: mobilnim uređajima i programatskim oglašavanjem. Dominacija mobilnih uređaja je apsolutna; 81% potrošnje na display oglašavanje (unutar kojeg video formati čine 44%) i 85% na video oglašavanje usmjereno je na mobilne platforme. Na društvenim mrežama vlada gotovo potpuni duopol, gdje platforme tvrtke Meta (Facebook 51,5% i Instagram 43,5%) privlače oko 95% svih oglašivačkih budžeta, dok u segmentu video oglašavanja YouTube (53%) i Facebook (29%) zajedno kontroliraju 82% tržišta. Istovremeno, programatsko oglašavanje postaje standard; 64% display oglasa već se kupuje na taj način, a očekuje se da će taj udio do 2028. dosegnuti 75% ukupnog digitalnog oglašavanja. Cjenovna dinamika odražava status tržišta u razvoju, s cijenama po kliku na Google Ads oglasima koje su u prosjeku 63% niže od američkih. Regulativa, primarno GDPR i Zakon o elektroničkim komunikacijama, postavlja stroge okvire za privole i korištenje podataka, uz aktivan nadzor nadležne agencije koja je u 2022. provela 1.140 inspekcijskih postupaka.

Sve se to odvija na temeljima infrastrukture koja je također paradoksalna. S jedne strane, Hrvatska se može pohvaliti izvanrednom pokrivenošću 5G mrežom od 97,5% populacije (na frekvencijama n28 i n78) i modernizacijom koja uključuje gašenje 3G mreže u siječnju 2025. Mobilne brzine interneta porasle su na 88,24 Mbps (40. mjesto u svijetu). S druge strane, fiksni širokopojasni internet značajno zaostaje: brzina od 62,16 Mbps svrstava nas tek na 90. mjesto globalno. Pokrivenost optičkom mrežom (FTTP) od 39% i mrežama vrlo visokog kapaciteta (VHCN) od 52% znatno su ispod EU prosjeka od 50% i 70%. Upravo taj neujednačeni razvoj, gdje mobilna infrastruktura daleko nadmašuje fiksnu, objašnjava "mobile-first" ponašanje hrvatskih korisnika. Tome doprinosi i gustoća mobilnih priključaka od 132,9%. nadmašuje fiksnu, objašnjava "mobile-first" ponašanje hrvatskih korisnika.

# Digitalna budućnost između europskih ciljeva i lokalnih ograničenja

Hrvatska se prema Indeksu digitalnoga gospodarstva i društva (DESI) nalazi na 21. mjestu od 27 članica EU, u skupini sa zemljama poput Grčke, Bugarske i Rumunjske, daleko od lidera kao što su Finska i Danska. To je odraz opisanog neujednačenog napretka. Dok su ljudski kapital (59% s osnovnim vještinama vs. 55,6% u EU) i stupanj digitalizacije poduzeća (14. mjesto u EU) relativno snažne točke, slabe karike ostaju povezivost i digitalne javne usluge. Hrvatska poduzeća pokazuju iznimnu sposobnost usvajanja tehnologije (čak 65,6% koristi AI, oblak ili velike podatke naspram 54,6% u EU), ali se suočavaju s nedostatkom ICT stručnjaka, kojih je 4,3% u radnoj snazi naspram 4,8% u EU.

Buduća putanja hrvatskog digitalnog ekosustava bit će definirana napetošću između značajnih prilika i dubokih strukturnih ograničenja. Prilike leže u digitalizaciji turizma, natprosječnoj digitalnoj pismenosti mladih i potencijalu ICT sektora, koji se očituje u uspjehu prvog hrvatskog jednoroga, tvrtke Infobip, te McKinseyevim projekcijama prema kojima bi digitalna ekonomija mogla narasti s 4,5% na 15% BDP-a do 2032. godine. Postoji i jasna javna podrška, jer 83% Hrvata vjeruje da digitalizacija olakšava život, naspram 73% u EU. Međutim, demografski vjetrovi – starenje, pad broja stanovnika i cjenovna osjetljivost – predstavljaju fundamentalna ograničenja rasta. Za informativne medije, egzistencijalna kriza ostaje bez očitog rješenja. Bez radikalnih promjena u poslovnim modelima, regulatornog okvira koji štiti novinare i potiče transparentnost, te obnove povjerenja publike, medijski pluralizam ostat će pod stalnom prijetnjom. Konačni izazov za cjelokupni ekosustav nije, dakle, usvajanje globalnih tehnologija – što je Hrvatska uvelike već učinila – već stvaranje održivih monetizacijskih modela prilagođenih specifičnoj ekonomiji i demografiji malog, starenjem opterećenog i cjenovno osjetljivog tržišta

# Od makro-slike do mikro-dokaza: Uvod u empirijsku analizu medijskog diskursa

Prethodna analiza pružila je sveobuhvatan, makro-razinski pregled hrvatskog digitalnog medijskog ekosustava. Identificirala je ključne strukturne napetosti: jaz između visoke penetracije i niske monetizacije, krizu povjerenja, utjecaj inozemnog vlasništva te duboki generacijski rascjep. Ti su zaključci, izvedeni sintezom javno dostupnih statistika, industrijskih izvješća i postojećih akademskih istraživanja, nužan prvi korak. Oni su poput zračne fotografije grada: pružaju nam uvid u raspored ulica, veličinu zgrada i opće obrasce, ali nam ne otkrivaju život koji se odvija na tim ulicama. Makro-podaci nam pokazuju što se događa – pad povjerenja je mjerljiva činjenica – no ostaju nijemi na pitanje kako se taj proces odvija u stvarnom vremenu. Ne mogu nam pokazati kako se specifični narativi, potekli od određenih medijskih aktera, šire, mutiraju i doprinose eroziji povjerenja iz dana u dan.

Kako bismo prešli s te statične slike na dinamičan film, odnosno s deskriptivne na eksplanatornu razinu analize, nužan je metodološki zaokret. Potrebno je zaroniti u sam "krvotok" digitalnog ekosustava i pratiti interakcije koje ga čine živim. Upravo stoga, u nastavku uvodimo i detaljno opisujemo jedinstven, do sada neobjavljen i nejavno dostupan skup podataka. Riječ je o podatkovnoj osnovi koja omogućuje granularan uvid u svakodnevnu proizvodnju i recepciju medijskog sadržaja. Korištenjem ovog alata, u mogućnosti smo preći s općih trendova na specifične mehanizme – informacijske kaskade, cikluse angažmana i kompetitivne strategije medija – te tako proširiti, produbiti i empirijski testirati spoznaje opisane u prvom dijelu ovog poglavlja.

# Empirijska osnova za proširenu analizu: Longitudinalni skup podataka (2021. – 2024.)

Okosnicu novog analitičkog pristupa čini opsežan, longitudinalni skup podataka, osmišljen specifično za mapiranje i proučavanje hrvatskog digitalnog medijskog ekosustava. U svojoj suštini, ovaj skup podataka funkcionira kao sveobuhvatan arhiv javne medijske aktivnosti, obuhvaćajući sve ključne digitalne platforme tijekom četverogodišnjeg razdoblja. S približno 25 milijuna pojedinačnih medijskih objava prikupljenih u razdoblju od 2021. do 2024. godine, on pruža bogatu, višedimenzionalnu osnovu za kvantitativnu analizu medijskih trendova, uspješnosti pojedinih aktera te dinamike javnog diskursa u hrvatskom digitalnom prostoru.

Osnovne karakteristike ovog skupa podataka definiraju njegovu analitičku snagu. Vremenski okvir od četiri godine (2021. – 2024.) omogućuje ne samo praćenje dugoročnih trendova i sezonskih obrazaca, već i preciznu analizu reakcija medijskog sustava na specifične događaje, poput izbornih ciklusa ili društvenih kriza. Opsegom pokriva cjelokupni hrvatski digitalni medijski krajolik. Uključivanjem sadržaja s mrežnih portala (npr. 'Jutarnji list', 'Index.hr'), društvenih medija (Facebook, Twitter, Instagram, TikTok) i video platformi (YouTube), ovaj skup podataka prevladava ograničenja studija fokusiranih na samo jednu platformu i nudi istinski holistički, ekosustavski pogled. Granularnost je postavljena na razinu pojedinačne, jedinstvene medijske objave, što znači da svaki zapis u bazi predstavlja jedan novinski članak, jednu objavu na Facebooku ili jedan videozapis na YouTubeu, omogućujući time mikro-razinsku preciznost.

# Struktura podataka i analitički potencijal varijabli

Struktura podataka, s 49 varijabli za svaku od 25 milijuna objava, može se podijeliti u četiri ključne skupine koje zajedno tvore cjelovitu sliku svake objave.

1.  Podaci o tekstualnom sadržaju: Ovo je narativno srce svake objave. Varijable TITLE (naslov) i FULL_TEXT (cjeloviti tekst) predstavljaju temelj za dubinsku analizu sadržaja. Primjenom računalnih metoda obrade prirodnog jezika (NLP), moguće je ići dalje od pukog čitanja. Korištenjem tematskog modeliranja na varijabli FULL_TEXT, možemo empirijski mapirati dominantne tematske preokupacije cjelokupnog medijskog prostora, pratiti kako određene teme (npr. ekonomska kriza, vanjska politika) dobivaju na važnosti dok druge bivaju marginalizirane te identificirati ključne "okvire" (engl. frames) kroz koje mediji interpretiraju događaje. Analiza sentimenta na varijabli TITLE omogućuje, pak, kvantifikaciju tonaliteta medijskog izvještavanja o određenim akterima ili temama.

2.  Metapodaci o izvoru i vremenu: Ako je tekstualni sadržaj "što", ove varijable odgovaraju na pitanja "tko, gdje i kada". Precizne vremenske oznake (DATE, TIME, DATETIME) nisu samo deskriptori; one su ključ za razumijevanje temporalne dinamike medija. Analizom ovih varijabli možemo mjeriti brzinu širenja vijesti – takozvane informacijske kaskade – prateći put jedne priče od prve objave na web portalu (SOURCE_TYPE: 'web') do njezine amplifikacije i transformacije na društvenim mrežama (SOURCE_TYPE: 'facebook'), mjereći pritom vremenski odmak i mutacije poruke. Varijabla FROM (izvor) je najvažniji alat za analizu medijskih aktera, omogućujući izravnu usporedbu njihovih sadržajnih strategija, volumena produkcije i dosega.

3.  Metrike angažmana publike i viralnosti: Ove varijable kvantificiraju "život" objave nakon što je puštena u javnost. One su izravan pokazatelj recepcije i rezonancije sadržaja kod publike. Agregatna mjera INTERACTIONS pruža brzi uvid u ukupni odjek. No, dublja analiza njezinih komponenti (LIKE_COUNT, COMMENT_COUNT, SHARE_COUNT) nudi nijansiraniju sliku: visok broj lajkova uz nizak broj komentara može ukazivati na pasivno odobravanje, dok eksplozija komentara često signalizira kontroverzu ili polarizaciju. Broj dijeljenja (SHARE_COUNT) ostaje najpouzdaniji pokazatelj organskog širenja i viralnog potencijala. Konačno, normalizirana metrika ENGAGEMENT_RATE djeluje kao "analitički equalizer": ona stavlja u ravnopravan položaj objavu velikog medija s milijun pratitelja i objavu malog, nišnog portala, mjereći relativnu učinkovitost sadržaja u poticanju interakcije.

4.  Metrike dosega i veličine publike: Ova skupina varijabli pomaže razlikovati potencijalnu od stvarne vidljivosti. FOLLOWERS_COUNT (broj pratitelja) definira maksimalni potencijalni auditorij jedne objave. S druge strane, REACH (doseg) daje procjenu stvarnog broja jedinstvenih korisnika koji su bili izloženi sadržaju, što je realnija mjera vidljivosti. Važno je razlikovati doseg od viralnosti: doseg može biti rezultat plaćene promocije, dok je VIRALITY (viralnost) – sofisticirana izračunata metrika – osmišljena da procijeni intrinzičnu "zaraznost" sadržaja, odnosno njegovu sposobnost da potakne korisnike na organsko, eksponencijalno širenje. Metaforički rečeno, FOLLOWERS_COUNT je veličina razglasa, REACH je broj ljudi do kojih je zvuk dopro, a VIRALITY je privlačnost same poruke koja tjera ljude da je prenose dalje.

# Metodološka snaga i inherentna ograničenja

Sinergija ovih varijabli pruža iznimnu metodološku snagu. Sveobuhvatnost skupa podataka omogućuje analize na više razina s visokim statističkim pouzdanjem. Holistički pristup, koji obuhvaća sve ključne platforme, pruža jedinstvenu priliku za analizu prelijevanja sadržaja i utjecaja između različitih dijelova ekosustava, nudeći pogled koji nadilazi metodološke silose.

Istovremeno, akademska strogost nalaže priznavanje inherentnih ograničenja. Najvažnije je odsustvo demografskih podataka o publici; skup podataka ne otkriva dob, spol, obrazovanje ili lokaciju korisnika koji su u interakciji sa sadržajem. To znači da se naša analiza usredotočuje na strukturu i dinamiku diskursa, a ne na njegovu recepciju od strane specifičnih društvenih skupina. Drugo, skup podataka obuhvaća isključivo javno dostupne objave, dok sadržaj iz zatvorenih grupa, privatnih poruka i drugih nejavnih kanala ostaje izvan dohvata. Konačno, ključno je prepoznati utjecaj algoritamske neprozirnosti (engl. algorithmic opacity). Platformski algoritmi funkcioniraju kao "metodološka crna kutija" koja presudno utječe na vidljivost sadržaja. Naša analiza stoga ne može objasniti rad samih algoritama, već se fokusira na mjerenje njihovih vidljivih ishoda – angažmana, dosega i viralnosti. Unatoč tim ograničenjima, ovaj skup podataka predstavlja jedinstven i najopsežniji empirijski alat za produbljivanje spoznaja o hrvatskom digitalnom medijskom prostoru do sada
