---
title: "Google"
subtitle: ""
author: "Lux"
date: today
lang: hr
format:
  html:
    toc: true
    toc-depth: 3
    toc-title: "Sadržaj"
    number-sections: true
    theme: cosmo
    code-fold: true
    embed-resources: true
    fontsize: 11pt
  pdf:
    toc: true
    toc-depth: 3
    number-sections: true
    documentclass: report
    fontsize: 11pt
    geometry: margin=2.5cm
    include-in-header:
      text: |
        \usepackage{fancyhdr}
        \pagestyle{fancy}
        \fancyhead[L]{Algoritamski Suveren}
        \fancyhead[R]{Google i hrvatski medijski ekosustav}
---

# Uvod

Ovo poglavlje daje prikaz transformacije Googlea iz pružatelja usluga u **infrastrukturnog suverena** hrvatskog digitalnog medijskog ekosustava kroz sveobuhvatan sustav ekonomske ekstrakcije, algoritamskog čuvarenja pristupa i tehnološke ovisnosti koji je fundamentalno restrukturirao uvjete novinarske proizvodnje, distribucije informacija i demokratskog diskursa. Kontrolom pretraživanja sa tržišnim udjelom od 97,02 posto, mobilnih operacijskih sustava kroz dominaciju Androida, web preglednika Chrome, oglašivačke tehnologije putem vertikalne integracije kroz cijeli programatski lanac te sve više sustava umjetne inteligencije koji sintetiziraju sadržaj bez kompenziranja kreatora, Google izvršava ono što predstavlja **privatno upravljanje** hrvatskom digitalnom javnom sferom.

Politička ekonomska analiza otkriva sistematsku ekstrakciju vrijednosti koja djeluje kroz više dimenzija. Google i Meta zajedno kontroliraju preko 70 posto hrvatskog tržišta digitalnog oglašavanja vrijednog 222 milijuna eura, pri čemu Google kontrolira procijenjenih 96 milijuna eura samo u oglašavanju pretraživanja. Vertikalno integrirani ad-tech lanac, gdje Google istovremeno predstavlja kupce, prodavače i upravlja burzom, ekstrahira između 49 i 70 posto oglašivačkih izdataka prije nego izdavači prime plaćanje. Hrvatske redakcije proizvode sadržaj koji privlači publiku, ali Googleovi intermedijalni sustavi zarobljavaju većinu ekonomske vrijednosti, ostavljajući izdavačima opadajuće prihode unatoč rastućem prometu.

Algoritamska ovisnost stvara ono što se može nazvati "stupica suvereniteta" gdje Google Discover i pretraživanje određuju vidljivost, a time i održivost digitalnih medijskih kuća, no algoritamski kriteriji ostaju neprozirni i volatilni. Jedno ažuriranje algoritma može eliminirati između 30 i 40 posto prometa portala preko noći, čineći dugoročno uređivačko planiranje nemogućim. To stvara pritisak prema senzacionalizmu, klikbejtu i optimizaciji sadržaja za metrike angažmana umjesto za građansku vrijednost.

Hrvatski korisnici interneta s 93-postotnom stopom penetracije u populaciji od 3,8 milijuna ljudi izvršavaju ono što znanstvenici nazivaju "digitalnim radom", generirajući bihevioralne podatke kroz pretraživanja, klikove i interakcije koje Google ekstrahira, rafinira i monetizira. "Roba publike" na malom hrvatskom tržištu postaje posebno vrijedna upravo zbog oskudnosti podataka, jer Googleova granularna mogućnost praćenja kroz uređaje, usluge i web stranice stvara preciznost ciljanja koju lokalni izdavači ne mogu oponašati, sistematski stavljajući hrvatske medijske kuće u nepovoljan položaj u aukcijama oglašavanja koje se provode na Googleovoj vlastitoj infrastrukturi.

Akvizicija Photomath aplikacije iz Hrvatske od strane Googlea 2023-24 predstavlja udžbenički primjer ekstrakcije iz centra prema periferiji. Umjesto da se razvije u neovisnu tehnološku kompaniju koja bi mogla usidriti hrvatski digitalni ekosustav, Photomathove sposobnosti umjetne inteligencije sada poboljšavaju Googleove globalne proizvode dok vrijednost pripada dioničarima Alphabeta. Ova dinamika "podružničnog pogona" pojačava strukturnu ovisnost gdje periferijska tržišta proizvode inovaciju koju zahvaćaju središta.

Lansiranje Googlea News Showcase u Hrvatskoj u veljači 2025. godine s licenciranjem sadržaja od 24sata, Večernjeg lista, Index.hr i Net.hr ne predstavlja redistribuciju vrijednosti već konstrukciju onoga što ovaj izvještaj naziva "zlatnim kavezom". Izdavači primaju zajamčena plaćanja koja pružaju kratkoročno financijsko olakšanje usred urušavanja prihoda od tiska i stagnantnih programatskih stopa, ali integracija u Googleov ekosustav produbljuje ovisnost, slabi izravne odnose s publikom i ubrzava tržišnu konsolidaciju privilegiranjem odabranih velikih igrača dok isključuje manje neovisne medije.

Nadolazeće uvođenje AI Overviews predstavlja ono što promatrači industrije karakteriziraju kao "događaj na razini izumiranja". Sintetiziranjem sadržaja od hrvatskih izdavača izravno unutar rezultata pretraživanja bez kompenzacije, čak i kada su izdavači isključili obuku umjetne inteligencije, Google fundamentalno prepisuje razmjenu vrijednosti koja je održavala otvoreni web. Brojne studije dokumentiraju pad prometa od 60 do 80 posto za izdavače kada se pojavljuju AI Overviews, a pretraživanja bez klikova povećala su se sa 56 posto na 69 posto između svibnja 2024. i svibnja 2025. godine. Hrvatski mediji poput Index.hr, Večernjeg lista i 24sata suočavaju se s izgledima proizvodnje novinarstva koje trenira sustave umjetne inteligencije u vlasništvu stranih korporacija, pri čemu korisnici konzumiraju sintetizirane verzije koje eliminiraju i prihod od oglašavanja i pripisivanje brenda.

Googleova inicijativa "Rasti s Googleom" koja je između 2017. i 2020. obučila preko 37 tisuća Hrvata u partnerstvu s Hrvatskim zavodom za zapošljavanje ne predstavlja digitalno osnaživanje već ono što kritički znanstvenici nazivaju "zarobljavanjem mekih moći". Podučavajući Google Ads, Google Analytics i Google My Business kao univerzalne digitalne vještine, program učinkovito premješta troškove obuke radne snage na hrvatske porezne obveznike dok utvrđuje buduću potražnju za Googleovim vlasničkim ekosustavom. Partnerstva sa sveučilištima poput VERN Sveučilišta integriraju platformsku logiku u visoko obrazovanje, podučavajući studente da gledaju na ekstrakciju podataka i algoritamski marketing kao neutralne tehničke kompetencije umjesto kao na osporeni politički teren.

Analiza zaključuje da hrvatski mediji ne djeluju unutar konkurentskog tržišta već unutar sustava **infrastrukturnog imperijalizma** gdje sudjelovanje u digitalnom društvu zahtijeva kretanje kroz infrastrukturu u Googleovom vlasništvu, generiranje podataka koji hrane Googleov model nadzornog kapitalizma i natjecanje pod algoritamskim pravilima koja sistematski favoriziraju platformu nad izdavačima. Bez agresivne regulatorne intervencije Europske unije, strukturnih pravnih sredstava uključujući potencijalnu prodaju Chromea i razdvajanje ad-tech lanca te reimaginirane digitalne javne infrastrukture, hrvatski medijski ekosustav riskira postati ono što ovaj izvještaj naziva "šupljom ljuskom", skupom ovisnih proizvođača sadržaja koji hrane suveren umjetne inteligencije koji služi interesima Alphabet Inc. umjesto hrvatskom demokratskom diskursu.

# Digitalna ograda hrvatske javne sfere

Transformacija hrvatskog medijskog krajolika tijekom posljednja dva desetljeća nije rezultirala decentraliziranom, demokratiziranom javnom sferom koju su zamišljali rani zagovornici interneta. Umjesto toga, ekosustav se sažeo u visoko stratificiranu "platformiziranu" ekonomiju gdje fundamentalne uvjete proizvodnje, distribucije i monetizacije sve više diktiraju transnacionalni monopoli, najznačajnije Alphabet Inc., matična kompanija Googlea. Ovaj izvještaj pruža iscrpnu, politički ekonomski utemeljenu analizu Googleovih operacija u Hrvatskoj, argumentirajući da kompanija ne funkcionira samo kao neutralni pružatelj usluga ili tržišni sudionik već kao infrastrukturni suveren koji izvršava duboku strukturnu moć nad hrvatskim digitalnim ekosustavom.

U kontekstu malog, polu-perifernog tržišta unutar Europske unije, Hrvatska predstavlja specifičan tip digitalnog teritorija: onaj koji je visoko povezan s penetracijom interneta koja dostiže 93 posto, no strukturno ovisan o stranim tehnološkim lancima. Odnos između hrvatskih izdavača, države i Googlea karakteriziran je asimetričnom ovisnošću. Dok Google pruža esencijalnu infrastrukturu za promet kroz pretraživanje i Discover te prihod kroz AdSense i Ad Manager, on istovremeno ekstrahira goleme količine podataka predstavljajući ono što kritički znanstvenici nazivaju "robom publike", erodira distinktivnu vrijednost lokalnog novinarstva kroz algoritamsku komodifikaciju i zarobljava razvojnu putanju lokalne digitalne ekonomije kroz inicijative poput "Rasti s Googleom".

Ova analiza crpi iz kritičkih tradicija političke ekonomije komunikacije, koristeći teorijske okvire "robe publike" Dallasa Smythea, "digitalnog rada" kako ga konceptualiziraju Christian Fuchs i Paško Bilić te koncept "digitalnog kolonijalizma". Sintetizira podatke Hrvatskog udruženja digitalnih izdavača HUDI, Agencije za elektroničke medije, IAB Croatia i različitih akademskih i industrijskih izvora kako bi mapirala konture ove digitalne hegemonije. Izvještaj služi kao korektiv tehno-optimističkim narativima koje često promiču inicijative korporativne društvene odgovornosti, otkrivajući umjesto toga ekstraktivnu logiku koja podupire digitalnu tranziciju u jugoistočnoj Europi.

# Teorijski okvir: Platformski kapitalizam na polu-periferiji

Za razumijevanje specifičnosti Googleovog utjecaja na Hrvatsku potrebno je prvo situirati lokalno tržište unutar šireg konteksta globalnog platformskog kapitalizma. Kao što primjećuje hrvatski znanstvenik Paško Bilić, digitalna ekonomija nije beskonačna ravnina jednakih mogućnosti već hijerarhijski organiziran sustav gdje vrijednost teče s periferije prema centru.

## Roba publike i digitalni rad

Temeljna koncepcija za ovu analizu je Smytheova "roba publike" koja postavlja da je primarni proizvod masovnih medija nije sadržaj, odnosno vijesti, već pažnja publike prodana oglašivačima. U digitalnom dobu, ovo je evoluiralo u ono što znanstvenici opisuju kao "prosumer komodifikaciju". Hrvatski korisnici u svojim svakodnevnim interakcijama s Google pretraživanjem, YouTubeom i Android uređajima izvršavaju neplaćeni "digitalni rad". Oni generiraju bihevioralni višak, podatke o lokaciji, namjeri, preferencijama i društvenim vezama koje Google procesira i pakira.

Na malom tržištu poput Hrvatske s populacijom od približno 3,8 milijuna stanovnika, oskudnost podataka paradoksalno povećava vrijednost Googleovih granularnih mogućnosti ekstrakcije. Lokalni izdavači, nemajući masivne baze prijavljenih korisnika i mogućnosti praćenja kroz različite stranice koje ima Alphabet, ne mogu se natjecati s preciznošću ciljanja koju Google nudi. Posljedično, vrijednost koju stvara hrvatska publika uglavnom zarobljavaju platforme umjesto kreatora sadržaja. Bilić i Primorac istaknuli su "jaz u digitalnom oglašavanju" u Hrvatskoj, gdje porast u online potrošnji ne korelira s proporcionalnim porastom prihoda izdavača jer višak odsisavaju intermedijari.

Ova dinamika nije jedinstvena za Hrvatsku već predstavlja globalnu obrazac što marxistički teoretičari označavaju kao "akumulaciju putem dispozicije" u digitalnom dobu. Vrijednost koju stvaraju radnici digitalne komunikacije (korisnici, kreatori sadržaja, novinari) sistematski se aproprijira putem kontrole infrastrukture i vlasništva nad sredstvima za distribuciju. Google ne posjeduje hrvatske medijske kuće u tradicionalnom smislu vlasništva nad dionicama, već kontrolira nešto fundamentalnije: infrastrukturu kroz koju se sadržaj distribuira i mehanizme kroz koje se monetizira.

## Digitalni kolonijalizam i infrastrukturni imperijalizam

Dinamika opažena u Hrvatskoj rezonira s teorijom "digitalnog kolonijalizma". Ovaj okvir sugerira da multinacionalne tehnološke divove učinkovito koloniziraju digitalnu infrastrukturu nacija, kontrolirajući "teritorij" kroz servere, oblake i operacijske sustave te ekstrahirajući "resurse" u obliku podataka i intelektualnog vlasništva dok lokalna država zadržava samo nominalnu suverenost.

Googleova dominacija u Hrvatskoj je infrastrukturna. Kompanija kontrolira operacijski sustav Android, preglednik Chrome, tražilicu, platformu za hosting videa YouTube i ad-tech lanac. Ova vertikalna integracija znači da za hrvatskog građanina koji želi sudjelovati u digitalnom društvu, čitati vijesti, pronaći posao ili naučiti vještinu, mora prečiti infrastrukturu u Googleovom vlasništvu. Inicijativa "Rasti s Googleom", koju ćemo detaljnije analizirati kasnije, može se promatrati kroz ovu leću kao mehanizam meke moći za učvršćivanje ove ovisnosti obučavajući lokalnu radnu snagu da koristi i oslanja se na kolonizatorove alate.

Povijesni kolonijalizam uključivao je teritorijalnu kontrolu fizičkog prostora, ekstrakciju sirovina, tržišni kaptivitet gdje kolonije služe kao zarobljeni kupci proizvoda metropole, kulturnu hegemoniju kroz nametanje jezika i obrazovnih normi te infrastrukturnu ovisnost gdje su transportni i komunikacijski sustavi dizajnirani da olakšaju ekstrakciju umjesto lokalnog razvoja. Digitalni kolonijalizam ponavlja ove obrasce kroz kontrolu nad kibernetskim prostorom, ekstrakciju bihevioralnih podataka, monopolizaciju digitalnih tržišta, ideološku naturalizaciju platformske logike i infrastrukturnu ovisnost gdje sudjelovanje u digitalnoj ekonomiji zahtijeva korištenje platformi čija je sjedišta i kontrola u stranim jurisdikcijama.

Hrvatsko iskustvo demonstrira kako digitalni kolonijalizam ne djeluje kroz otvorenu prinudu već kroz ono što Antonio Gramsci bi nazvao "hegemonijom" kombinacijom sile i konsenzusa gdje je dominacija normalizirana kroz svakodnevne prakse do te mjere da alternative postaju nemislive. Kada hrvatski srednjoškolci uče koristeći Google Classroom, kada hrvatska poduzeća oglašavaju kroz Google Ads, kada hrvatski novinari koriste Google Analytics da razumiju svoju publiku, oni ne doživljavaju to kao podređivanje stranoj kontroli već kao normalno funkcioniranje u digitalnom svijetu. Hegemonija je uspješna kada se izvedena priroda društvenih aranžmana učini nevažnom, kada su historijski konstruirane relacije moći predstavljene kao tehnički nužne.

## Zlatni kavez i asimetrično partnerstvo

Koncept "zlatnog kaveza" opisuje odnose gdje kratkoročne koristi stvaraju dugoročnu ovisnost koja potkopava autonomiju. Plaćanja kroz News Showcase, iako neotkrivena ali dio Googleove globalne obveze od milijardu dolara, pružaju ključan prihod hrvatskim izdavačima koji se suočavaju s više simultanih kriza.

Tiskana naklada u Hrvatskoj urušila se sa 640 tisuća na 300 tisuća primjeraka dnevno između 2008. i 2013. godine, dok je oglašavanje u tisku palo sa 104 milijuna eura 2008. na samo 36 milijuna eura 2015. godine. Zatvaranje Tiska d.o.o., dominantne hrvatske distributivne kompanije za tisak 2024. godine, označilo je još jedan prijelomni trenutak u padu tradicionalnih medija. Dok se ukupni prihod od oglašavanja oporavio na približno 266 milijuna eura do 2023., digitalni dio sve više teče prema stranim platformama umjesto lokalnim izdavačima. Komercijalna televizija je u stranom vlasništvu više od dva desetljeća kroz United Group i CME, a glavni tiskani naslovi djeluju pod austrijskim i njemačkim vlasništvom kroz Styria i Hanza Media.

U ovom kontekstu, plaćanja kroz News Showcase pojavljuju se kao "život spasonosno uže". No, politička ekonomija otkriva asimetričnu moć. Ono što izdavači dobivaju uključuje zajamčeni mjesečni prihod u nedefiniranim iznosima, poboljšanu vidljivost u Google News i Discover, mogućnost "kuriranja" kako bi odabrali sadržaj za prikazivanje te asocijaciju s Googleovim brendom koja pruža legitimnost. No, ono što Google dobiva daleko premašuje te eksplicitne koristi. Licenciranje sadržaja uklanja pravne vulnerabilnosti u vezi s intelektualnim vlasništvom, a produbljivanje integracije izdavača u Googleov ekosustav povećava prelazne troškove potencijalnog izlaska. Regulatorna legitimnost kroz mogućnost tvrdnje "plaćamo izdavače" u regulatornim raspravama smanjuje pritisak za sistemske reforme poput razdvajanja ad-tech lanca ili označavanja kao common carrier. 

Dodatno, Google dobiva podatke o kuratorskim odlukama izdavača, otkrivajući što urednici smatraju svojim najkvalitetnijim radom, angažman korisnika unutar Googleovih svojstava umjesto na stranicama izdavača te precendent koji čini buduća pregovaranja sa drugim izdavačima lakšima kada mogu pokazati postojeća partnerstva. S druge strane, izdavači gube polugu da zahtijevaju reforme ad-tech sustava, izravne odnose s publikom kako potrošnja prelazi na Googleov interface, pregovaračku moć kada prihvaćanje stvara precedent za buduće uvjete te raznolikost tržišta kako stratifikacija privilegira odabrane partnere.

Metafora "zlatnog kaveza" zahvaća kako financijalno olakšanje dolazi s nevidljivim ograničenjima. Izdavači postaju ovisni o održavanju dobrih odnosa s Googleom, čineći zagovaranje za strukturne reforme strateškim rizikom. Hrvatsko novinarsko društvo i HUDI nalaze se u "frenemies" odnosu, nemogući antagonizirati infrastrukturnog pružatelja dok znajući da ta infrastruktura ih sistematski stavlja u nepovoljan položaj.

# Oglašavanje, podaci i duopol

Ekonomska osnova komercijalnog medijskog sustava Hrvatske historijski je bilo oglašavanje. No, migracija publike prema digitalnim kanalima otkačila je kreaciju sadržaja od generiranja prihoda. HUDI i IAB Croatia podaci otkrivaju tržište u fluksu. Hrvatsko online tržište oglašavanja nastavlja rasti, procijenjeno na preko 155 milijuna eura u 2024. godini, što predstavlja porast od 16,4 posto u odnosu na prethodnu godinu. No, ovaj agregatni rast prikriva distribucijsku krizu.

Značajan dio ove potrošnje u potpunosti zaobilazi lokalne proizvođače sadržaja, tečući umjesto toga u programatske ekosustave koje kontrolira "duopol" Googlea i Mete. Podaci iz 2022. godine dokumentiraju 96 milijuna eura uloženih u platforme za pretraživanje gdje Google uživa praktičan monopol te 62 milijuna eura u društvenim medijima gdje Meta dominira kroz Facebook i Instagram. Ovo predstavlja više od 160 milijuna eura od približno 222 milijuna eura ukupnog tržišta digitalnog oglašavanja, što ukazuje na koncentraciju preko 70 posto.

Dok display oglašavanje sa procijenjenih 36,7 posto tržišnog udjela naizgled podržava lokalne izdavače, supstancijalni udio ovog prihoda procesira se kroz Googleov ad-tech lanac uključujući Google Ad Manager, AdSense i AdExchange. Google ekstrahira rentu na više točaka u transakcijskom lancu. Na strani izdavača, Google naplaćuje naknade hrvatskim portalima da poslužuju oglase. Na strani oglašivača, Google naplaćuje hrvatskim kompanijama da postavljaju oglase. Na burzi, Google uzima udio od razlike u ponudama. Ovaj "ad-tech porez" smanjuje efektivni prihod koji zadržavaju hrvatske medijske kuće.

Prelazak na programatsko oglašavanje prisilio je hrvatske medije da prioritiziraju skalu nad kvalitetom. Da bi generirali dovoljan prihod od djelića centa zarađenih po programatskom impresiji, izdavači poput 24sata ili Index.hr moraju generirati masivne volumene prometa. Ovaj ekonomski imperativ gura "klikbejt" kulturu, senzacionalizam i masovnu proizvodnju sadržaja niske vrijednosti dizajniranog da potakne algoritamsko angažiranje umjesto da služi građanskim informacijskim potrebama.

Nadalje, dominacija YouTubea u video sektoru s dosegom od 82,7 posto hrvatskih korisnika interneta lišava lokalne emitera prihoda od digitalnog videa. Dok Nova TV i RTL imaju svoje VOD platforme, YouTube ostaje zadana destinacija za video sadržaj, prisiljavajući emitere da uploade svoje isječke na Googleovu platformu da održe relevantnost, efektivno trgovajući svojim sadržajem za vidljivost dok Google zadržava većinu prihoda od oglašavanja. Ovo predstavlja "obrnutu vrijednosnu lanac" gdje proizvođači sadržaja subvencioniraju platformsku infrastrukturu umjesto obrnuto.

## Vertikalno integrirani stroj za ekstrakciju vrijednosti

Googleova dominacija u ad-techu fundamentalno se razlikuje od tradicionalne tržišne moći zbog vertikalne integracije kroz cijeli transakcijski lanac. Američka Ministarstvo pravosuđa usporedilo je ovo sa "Goldman Sachs koji posjeduje New York Stock Exchange", scenarijem gdje jedan entitet istovremeno predstavlja prodavače kroz Google Ad Manager, upravlja burzom kroz Google AdX, predstavlja kupce kroz Google Ads, pruža tržišne podatke kroz Google Analytics koji pokazuje koji inventar funkcionira te kontrolira valutu kroz Googleove ID sustave koji sve više zamjenjuju kolačiće.

U hrvatskom kontekstu, ovo znači da kada hrvatski oglašivač koristi Google Ads da kupi display inventar na Index.hr, Google naplaćuje oglašivaču naknade i koristi podatke kroz više usluga da optimizira ciljanje. Aukcija se događa na Google AdX burzi gdje Google postavlja pravila aukcije, ima vidljivost u sve ponude kupaca i prodavača te može sudjelovati u aukcijama kroz Google AdSense koji se natječe protiv drugih potražnje. Index.hr prima pobjedničku ponudu kroz Google Ad Manager gdje Google naplaćuje naknade izdavaču, a izdavač vidi samo post-aukcijske informacije bez mogućnosti verifikacije pravednosti aukcije. Podaci zatim teku prema Google Analytics gdje Google uči koji sadržaj pokreće angažman, informacije koje može koristiti da optimizira vlastite proizvode poput Discovera i News. Na svakoj fazi, Google ekstrahira vrijednost, podatke i kontrolu.

ISBA studija otkrila je da izdavači primaju samo 51 posto potrošnje oglašivača u prosjeku, s programatskim lancima opskrbe koji zarobljavaju 49 posto. Udruga nacionalnih oglašivača dokumentirala je da izdavači primaju samo 30 do 40 centi po dolaru oglašivača. Za hrvatske izdavače koji već djeluju s tankim maržama, ova ekstrakcija može biti razlika između održivosti i zatvaranja.

Američka sudska presuda iz travnja 2025. godine potvrdila je ovu kritiku s historijskim presudama. Sudac Leonie Brinkema našao je da je Google "prekršio Section 2 Sherman Acta namjernim stjecanjem i održavanjem monopolske moći" na tržištima izdavačkih ad servera i ad exchangea, s time da je sud eksplicitno našao "nezakonito povezivanje" ad servera s exchangeom. Presuda primjećuje da je ovo ponašanje "supstancijalno naštetilo izdavačima i konačno potrošačima informacija na otvorenom webu". Kombinirano s više od 11 milijardi eura kumulativnih EU antitrust kazni uključujući 2,95 milijardi eura u rujnu 2025., pravni konsenzus se iskristalizirao: Googleova dominacija rezultira iz antikonkurentnog ponašanja, ne tržišne efikasnosti.

# Algoritamski suverenitet i "crna kutija" distribucije

Googleova moć nad javnim diskursom djeluje kroz tri međupovezana algoritamska sustava koja kolektivno određuju što milijarde ljudi vide, čitaju i vjeruju. Google pretraživanje procesira preko 8,2 milijardi upita dnevno koristeći više od 200 signala za rangiranje, pri čemu je ažuriranje jezgre u ožujku 2024. smanjilo ono što je Google smatrao "beskorisnim sadržajem" za 45 posto, što predstavlja odluku o moderaciji sadržaja koja utječe na pristup informacijama za stotine milijuna ljudi. YouTube sada analizira preko tisuću signala po videu, povećavši se sa prethodnih dvjesto, stvarajući monetizacijsko-algoritamske petlje povratnih informacija gdje videozapisi koji generiraju prihod primaju boostove vidljivosti, efektivno kodificirajući komercijalni uspjeh kao proxy za kvalitetu sadržaja.

Možda najznačajnije, Google Discover sada dostiže procijenjenih dva milijarde aktivnih korisnika i generira između 25 i 42 posto ukupnog organskog prometa za neke velike izdavače, često premašujući tradicionalno pretraživanje. Algoritamsko čuvanje stvara demonstrabilne efekte na medijski pluralizam. Istraživanja su kvantificirala povećanje ideološke segregacije od približno 18 posto zbog eho komora posredovanih platformama. UK studija Google Newsa našla je "malo dokaza o personalizaciji vijesti" ali otkrila "visoki stupanj homogenosti" gdje tradicionalne medijske marke sustavno dominiraju rezultatima, što osporava zabrinutosti oko filter balona dok podiže različite brige oko raznolikosti izvora.

## Monopol pretraživanja s 97,02 posto tržišnog udjela

Gotovo apsolutni monopol Google pretraživanja u Hrvatskoj s tržišnim udjelom od 97,02 posto daje mu unilateralnu kontrolu nad vidljivošću informacija. Za hrvatske izdavače, Google pretraživanje nije jedan od mnogih izvora prometa već primarni mehanizam kroz koji publike otkrivaju sadržaj. Presuda američkog antitrusta iz kolovoza 2024. otkrila je da je Google održavao svoj monopol na pretraživanju kroz ekskluzivne zadane sporazume plaćajući Apple, Mozilla, Samsung i Android proizvođačima milijarde da učine Google zadanom tražilicom, zahtjeve za preinstalaciju gdje Android proizvođači moraju preinstalirati Google pretraživanje kao uvjet za pristup Play Storeu te dijeljenje prihoda plaćajući 36 posto prihoda od Safari oglašavanja pretraživanjem Appleu da zadrži zadani status.

Sudac Amit Mehta zaključio je: "Google je monopolist i djelovao je kao takav da održi svoj monopol." Faza pravnog lijeka, u tijeku krajem 2024. i početkom 2025. godine, razmatra prodaju Chromea, prisilno prodavanje preglednika da razbije integrirani ekosustav koji pojačava dominaciju u pretraživanju. Za hrvatske izdavače, monopol stvara nekoliko ovisnosti.

Cijele odjele unutar hrvatskih redakcija fokusiraju se na "optimizaciju za tražilice", strukturirajući sadržaj, naslove, metadata i tehničku infrastrukturu da zadovolje Googleove algoritme za rangiranje. Ažuriranje jezgre iz ožujka 2024. godine, za koje je Google tvrdio da smanjuje "beskoristan sadržaj" za 45 posto, uzrokovalo je devastaciju prometa za izdavače globalno koji su našli svoj sadržaj iznenada reklasificiran. Hrvatski mediji nemaju resurse da brzo adaptiraju promjene algoritma koje veliki međunarodni izdavači mogu rasporediti timove da analiziraju.

Algoritamska neprozirnost dodatno komplicira situaciju. Googleovo rangiranje koristi "preko 200 signala", ali ponderiranje, interakcije i pragovi ostaju vlasnički. Izdavači moraju optimizirati za cilj koji se mijenja bez najave ili objašnjenja. Istraga Europske unije iz veljače 2025. o tome "demontira li Google sadržaj medijskih izdavača" priznaje da je ova neprozirnost dostigla razine regulatorne zabrinutosti. S tržišnim udjelom od 97,02 posto, ne postoji održiva alternativa. Bing, DuckDuckGo i druge tražilice kolektivno predstavljaju manje od tri posto hrvatskog prometa. Izdavač koji bojkotira Google pretraživanje efektivno bi sebe uklonio iz mogućnosti pronalaska.

## Google Discover i "stupica suvereniteta"

Google Discover predstavlja paradigmatski pomak od pretraživanja koje je zasnovano na namjeri i koje inicira korisnik prema feedu koji je zasnovan na interesima i koji algoritamski kurira. Discover sada dostiže procijenjene dvije milijarde aktivnih korisnika globalno i generira 25 do 42 posto ukupnog organskog prometa za neke velike izdavače, često premašujući tradicionalno pretraživanje. U Hrvatskoj, integracija Discovera na početni ekran Androida daje mu sveprisutnu vidljivost. Za mnoge korisnike, posebno mlađe demografije manje vezane uz izravne navike portala, Discover funkcionira kao primarno sučelje za otkrivanje vijesti.

Posljedice političke ekonomije su duboke. Za razliku od pretraživanja gdje izdavači mogu barem razumjeti namjeru iza upita i optimizirati sukladno tome, kriteriji kuriranja Discovera su gotovo u potpunosti neprozirni. Industrijska analiza sugerira faktore koji uključuju osobnu povijest pregledavanja i interese, signale "trendiranja" u stvarnom vremenu, rezultate "autoriteta" izdavača koji su sami po sebi neprozirni, "svježinu" sadržaja i brzinu ažuriranja te obrasce angažmana poput CTR i vremena provedenog na stranici.

Hrvatski urednici izvještavaju da je Discover u biti lutrija. Sadržaj se ili odabire i generira masivan promet ili uopće se ne pojavljuje, s malo predvidivosti. HUDI prezentacije opisuju pokušaje "obrnute inženjerije" onoga što Discover želi, što dovodi do uređivačkih distorzija. Ako se čini da Discover favorizira kriminalne priče, celebrity vijesti ili zdravstvene klikbejte, redakcije premještaju resurse prema tim temama bez obzira na građansku vrijednost. Nielsen i Reuters podaci koji pokazuju izravni pristup portalima u Hrvatskoj donekle ublažavaju ovo. Etablirani portali poput Index.hr mogu održati uređivačke standarde jer njihova lojalna publika dolazi izravno. No, za novije medije ili one koji traže rast publike, optimizacija za Discover postaje obavezna.

Volatilnost prometa također predstavlja značajan problem. Ažuriranja algoritma mogu eliminirati između 30 i 40 posto prometa izdavača preko noći. U ožujku 2024., nekoliko izdavača globalno prijavilo je takve padove nakon Googleovog "Helpful Content Updatea". Za hrvatske medije koji djeluju s tankim maržama, takva volatilnost sprječava dugoročno planiranje. Kako možete zaposliti istražni tim ako bi vaš prihod mogao nestati u ažuriranju algoritma? Ovo stvara ono što ovaj izvještaj naziva "stupicom suvereniteta", gubitkom uređivačke autonomije ne kroz izravnu cenzuru već kroz ekonomsku nužnost zadovoljavanja neprozirnog algoritma. Nije da Google govori hrvatskim urednicima što objavljivati, već distribucijski mehanizam stvara ekonomske poticaje koji oblikuju uređivačke odluke jednako učinkovito.

## Android kao operacijski sustav čuvara

Dominacija Androida na hrvatskom mobilnom tržištu, procijenjeno između 70 i 80 posto na temelju globalnih obrazaca i regionalnih podataka, pozicionira Google kao čuvara mobilnog operacijskog sustava. Ovo je važno jer zadane aplikacije na početnom ekranu Androida uključuju Google pretraživanje widget, Google Discover feed i Chrome preglednik kao zadane postavke. Iako korisnici mogu promijeniti ove postavke, istraživanje "efekta zadanih postavki" pokazuje da velika većina to nikada ne čini, što čini zadane postavke de facto monopolima.

Kontrola nad trgovinom aplikacija također je značajna. Google Play Store je primarni mehanizam za distribuciju aplikacija. Da bi hrvatski medij dosegnuo svoju publiku putem mobilne aplikacije, mora se pridržavati politika Play Storea uključujući ograničenja sadržaja i uvjete plaćanja, platiti 30-postotnu proviziju na kupovine unutar aplikacije iako je regulacija Europske unije prisilila neke promjene te prihvatiti Googleovu analitiku i izvještavanje o padovima što pruža podatke o korištenju Googleu i potencijalno se natjecati protiv Googleovog vlastitog agregiranja vijesti.

Lansiranje News Showcasea u Hrvatskoj u veljači 2025. uključuje integraciju "izravno u Android sučelje", što znači da se paneli vijesti pojavljuju unutar sloja operacijskog sustava, ne samo unutar aplikacija. Ovo predstavlja daljnju disintermediaciju gdje korisnici konzumiraju vijesti unutar Googleovog okruženja umjesto posjećivanja vlasništva izdavača, slabljenje odnosa izdavač-publika i smanjivanje mogućnosti prikupljanja podataka za izdavače. Kontrola operacijskog sustava stvara zaključavanje infrastrukture na najfundamentalnijoj razini gdje sudjelovanje u mobilnoj digitalnoj ekonomiji zahtijeva prihvaćanje Googleovih uvjeta, prikupljanja podataka i ekstrakcije prihoda.

## Chrome kao infrastruktura nadzora

Chromeov globalni tržišni udio od 64 do 72 posto s približno 3,98 milijardi korisnika pruža Googleu pervazivnu infrastrukturu nadzora koja pojačava njegovu moć u medijskoj industriji. Kako dokumentira ProMarket analiza, Chrome omogućava praćenje kroz različite stranice gdje Chromeova integracija s Googleovim uslugama znači da aktivnost korisnika kroz cijeli web teče u Googleove podatkovne sustave. Čak i kada posjećuju Index.hr ili Večernji list, hrvatski korisnici prijavljeni u bilo koju Google uslugu pružaju Googleu vidljivost u njihovo potpuno ponašanje pregledavanja.

Kontrola web standarda također je značajna. S tržišnim udjelom od više od 65 posto, Chrome efektivno kontrolira evoluciju web standarda. Google je suočen s kritikama od ad-tech industrije i zagovornika privatnosti zbog korištenja ove moći za odgađanje deprecijacije kolačića treće strane koja je više puta odgađana i konačno napuštena u korist "korisničkog izbora", predlaganje Privacy Sandbox alternativa koje kritičari kažu da bi učvrstile Googleovu prednost te implementiranje prijedloga Web Environment Integrity koji bi mogli omogućiti kontrole slične DRM-u.

Googleov AMP framework koji je bio intenzivno promoviran u rezultatima pretraživanja oko 2016. do 2020. godine, zahtijevao je od izdavača da hostiraju sadržaj na Googleovim serverima koristeći Googleov format. Dok je predstavljen kao optimizacija performansi, AMP je značio da je sadržaj serviran sa Googleove domene umjesto domene izdavača, Googleovi oglasi su se učitavali brže od vlastitih oglasa izdavača, korisnik je ostao unutar Googleovog ekosustava a izdavačka analitika je bila komplicirana Googleovom intermedijacijom. Mnogi izdavači uključujući hrvatske medije osjećali su se prisiljenima usvojiti AMP da održe vidljivost u pretraživanju, efektivno ustupajući hosting i kontrolu formata.

Googleova najava iz srpnja 2024. da ipak neće deprecirati kolačiće treće strane u Chromeu nakon godina pripreme industrije za alternative, primjer je kako je infrastruktura nadzornog kapitalizma toliko fundamentalna za Googleov poslovni model da čak ni kontinuirani regulatorni pritisak nije mogao prisiliti promjenu. UK Competition and Markets Authority podigao je zabrinutosti da bi Privacy Sandbox alternative učvrstile Googleovu dominaciju, ali ishod je bio čak i gori za izdavače: nastavljena ovisnost o kolačićima koje Google sa svojom bazom prijavljenih korisnika zapravo ne treba.

## YouTube i ekstrakcija radne snage sadržaja

YouTubeov doseg od 82,7 posto hrvatskih korisnika interneta čini ga zadanom platformom za konzumaciju videa s dubokim implikacijama za hrvatske emitere i kreatore sadržaja. Hrvatski emiteri poput Nova TV i RTL moraju uploadati isječke na YouTube da održe relevantnost društvenih medija i otkrivanje. No, YouTube zadržava većinu prihoda od oglašavanja, tipično 55 posto za YouTube i 45 posto za kreatora. Za profesionalno proizveden emitirani sadržaj, ovo predstavlja strukturnu inverziju gdje emiteri subvencioniraju Googleovu infrastrukturu umjesto da Google plaća za prava sadržaja kao u tradicionalnom licenciranju.

Kontrola algoritma preporuke je također ključna. YouTubeov algoritam preporuke, koji sada analizira preko tisuću signala po videu povećavši se sa prethodnih dvjesto, određuje koji sadržaj dostiže publike. Algoritam optimizira za "vrijeme gledanja" i "angažman", stvarajući dobro dokumentiranu dinamiku gdje senzacionalistički sadržaj prima disproporcionalnu vidljivost, duži videozapisi povijesno su primali preferencijalnu obradu, sličice i naslovi optimizirani za klikbejt nadmašuju informativne opise, a sadržaj na većim jezicima poput engleskog prima algoritamske prednosti nad manjim jezicima poput hrvatskog.

Barijere monetizacije također predstavljaju problem. YouTubeov Partner Program zahtijeva tisuću pretplatnika i četiri tisuće sati gledanja prije omogućavanja monetizacije. Za kreatora sadržaja na hrvatskom jeziku koji se suočava s maksimalnim tržištem od četiri do pet milijuna govornika uključujući Hrvatsku plus dijasporu, ovi pragovi su značajno teži za postići nego za kreatora na engleskom jeziku koji pristupa milijardama potencijalnih gledatelja. Asimetrija autorskih prava dodatno komplicira situaciju. YouTubeov Content ID sustav automatski detektira materijal zaštićen autorskim pravima i može blokirati videozapise u potpunosti, monetizirati videozapise sa svim prihodom koji ide vlasniku autorskih prava ili zahtijevati ručno rješavanje sporova koje je jako ponderirano prema vlasnicima autorskih prava.

Hrvatski emiteri često nalaze svoj vlastiti emitirani sadržaj često predmet copyright claima od različitih trećih strana, zahtijevajući birokratske procese spora da vrate monetizaciju na vlastiti sadržaj. U međuvremenu, YouTubeova skala čini ga u biti imuniziranim na ekvivalentne claimove. Odnos s platformom je strukturno asimetričan, demonstrirajući kako platformski kapitalizam radi na ekstrakciji vrijednosti iz proizvođača sadržaja dok zadržava kontrolu nad distribucijom i monetizacijom.

# AI Overviews i egzistencijalna prijetnja izdavačima

Uvođenje Googleovih AI Overviews, prethodno poznatih kao Search Generative Experience ili SGE, predstavlja najdublju transformaciju od Googleovog osnivanja i predstavlja ono što je NPR karakterizirao kao "događaj na razini izumiranja" za izdavače. Mehanizam funkcionira tako da kada korisnici pretražuju informacije, Googleova umjetna inteligencija sintetizira sadržaj iz više izvora i predstavlja izravan odgovor na vrhu rezultata pretraživanja. Korisnik čita odgovor unutar Googleovog sučelja, eliminirajući potrebu za klikom na bilo koju izvornu web stranicu.

Dokazi štete su devastirajući. Pew Research Center dokumentirao je 46,7-postotno relativno smanjenje CTR-a, Seer Interactive našao je 61-postotni pad organskog CTR-a, Ahrefs 34,5-postotno smanjenje za prvopozicionirane rezultate, dok je Authoritas dokumentirao do 79-postotno smanjenje CTR-a. Specifični utjecaji na izdavače uključuju CNN s približno 30-postotnim padom prometa iz godine u godinu, Business Insider i HuffPost s približno 40-postotnim padovima, DMG Media s do 89-postotnim padovima za određena pretraživanja te zatvaranje The Planet D nakon gubitka 90 posto prometa i Giant Freakin Robot u studenom 2024. citirajući AI Overviews.

Pretraživanja bez klikova povećala su se sa 56 posto na 69 posto između svibnja 2024. i svibnja 2025., što znači da više od dvije trećine pretraživanja sada završava bez ikakvog klika na vanjsku web stranicu. Za hrvatske izdavače, dok je AI Overviews rollout dostigao preko 200 zemalja i 40 jezika, sadržaj na hrvatskom jeziku suočava se s posebnim vulnerabilnostima.

Svjedočenje Googleovog potpredsjednika Eli Collinsa u svibnju 2025. na antitrust saslušanju otkrilo je da Google koristi sadržaj za AI Overviews čak i kada su izdavači isključili Gemini AI obuku. Hrvatski mediji poput Index.hr, Večernjeg lista i 24sata nemaju mehanizam da spriječe svoje novinarstvo od treniranja AI sustava koji ih onda zamjenjuju u rezultatima pretraživanja. Veliki jezični modeli funkcioniraju manje precizno u manjim jezicima s manje podataka za obuku. AI Overviews hrvatskog jezičnog sadržaja mogu uključivati greške ili pogrešne prijevode, šteteći reputaciji izdavača kada korisnici pretpostavljaju da je izdavač izvor.

Glavni međunarodni izdavači poput New York Timesa i Washington Posta tužili su ili pregovarali o sporazumima licenciranja s AI kompanijama. Hrvatski izdavači nemaju pravne resurse, tržišnu moć i međunarodnu vidljivost da prisile ekvivalentan tretman. Za izdavače koji već djeluju s tankim maržama, pad prometa od 30 do 60 posto bio bi katastrofalan. Ako AI Overviews dostignu punu implementaciju u Hrvatskoj, mediji poput Telegrama, Lupige ili regionalni portali poput Portal 072 mogli bi se suočiti sa zatvaranjem.

Kriza intelektualnog vlasništva pokrenula je val sudskih sporova. Preko desetak velikih tužbi sada je u tijeku globalno uključujući Penske Media Corp protiv Googlea iz rujna 2025., New York Times protiv OpenAI i Microsofta, Chegg protiv Googlea optužujući antitrust kršenja te kolektivne akcije izdavača u Kanadi, Indiji, Brazilu i Japanu. CEO News/Media Alliancea Danielle Coffey karakterizirala je Googleovo ponašanje kao "parazitsko, neodrživo i predstavlja realnu egzistencijalnu prijetnju." Hrvatski izdavači koji nemaju resurse da se pridruže ovim pravnim izazovima suočavaju se sa štetama bez pristupa pravnim lijekovima.

# Inicijativa "Rasti s Googleom" i zarobljavanje mekih moći

Googleova inicijativa "Rasti s Googleom" lansirana u partnerstvu s Ministarstvom rada i Hrvatskim zavodom za zapošljavanje obučila je preko 37 tisuća ljudi između 2017. i 2020. godine. Program se tipično karakterizira kao korporativna društvena odgovornost, benevolentni napor da se poboljša hrvatska digitalna pismenost i ekonomski oporavak nakon krize 2008. Kritička politička ekonomska analiza otkriva alternativne interpretacije.

Vještine koje se podučavaju fokusiraju se intenzivno na Googleov vlasnički ekosustav uključujući Google Ads za stvaranje i upravljanje oglašivačkim kampanjama, Google Analytics za analizu prometa web stranice i praćenje korisničkog ponašanja, Google My Business za vidljivost lokalnog poduzeća na Kartama i pretraživanju, YouTube za kreaciju sadržaja i optimizaciju te Google Workspace za produktivnost. Obučavajući hrvatsku radnu snagu u ovim specifičnim alatima, Google stvara buduću potražnju za svojim uslugama. Vlasnik malog poduzeća obučen da koristi Google Ads tri mjeseca vjerojatno neće kasnije preći na Microsoft Advertising ili hrvatsku alternativu jer su troškovi prebacivanja u obliku učenja novog sučelja i obnove kampanja barijere za konkurenciju.


Ovo predstavlja ono što znanstvenici nazivaju "zarobljavanjem ekosustava", ne kroz silu ili pravna ograničenja već kroz naturalizaciju. Googleovi alati postaju sinonim za "digitalne vještine" same po sebi, čineći alternative ne kao konkurente već kao devijacije od standarda. Partnerstvo s Hrvatskim zavodom za zapošljavanje efektivno premješta troškove obuke radne snage na hrvatske porezne obveznike. Tradicionalni poslovni modeli zahtijevaju od kompanija da obučavaju vlastitu korisničku bazu. Googleovo partnerstvo s HZZ-om omogućava da hrvatska vlada identificira nezaposlene ili nedovoljno kvalificirane građane, vlada pruža legitimnost i pristup te često fizičke objekte za obuku, Google pruža trenere često ugovoritelje i kurikulum, polaznici izlaze kao vješti korisnici Googleovog ekosustava, polaznici ulaze u hrvatska poduzeća i implementiraju Googleove alate, a Google dobiva kupce koje nije morao obučavati o vlastitom trošku.

Program izvještava o ishodima obuke fokusirajući se na "ekonomski oporavak" i "kreiranje poslova", ali ekonomska aktivnost koja se generira predominantno teče kroz Googleove platforme, s Googleom koji zarobljavaju prihod kroz oglašivačke naknade, prikupljanje podataka i pretplatničke usluge. Integracija sa sveučilištima i obrazovnim institucijama dodatno učvršćuje platformsku logiku. Program uključuje partnerstva s VERN Sveučilištem za integraciju kurikuluma digitalnih vještina, Algebrom za IT i digitalne marketing programe te različitim hrvatskim sveučilištima kroz gostujuća predavanja, radionice i programe certifikacije.

Integrirajući se u formalno obrazovanje, Googleova platformska logika postaje ugrađena u profesionalnu obuku. Studenti diplomiraju ne samo poznati s Googleovim alatima već misle u Googleovim kategorijama, mjere uspjeh kroz Google Analytics metrike, planiraju marketing oko Googleovih oglašivačkih opcija i razumiju "vidljivost" kao sinonim za rangiranje Google pretraživanja. Ova ideološka dimenzija je ključna jer studenti uče gledati na ekstrakciju podataka i algoritamski marketing ne kao osporeni politički teren već kao neutralne potrebne kompetencije za modernu ekonomiju. Kritička perspektiva da ovo predstavlja nadzorni kapitalizam, da postoje alternative i da bi regulatorna intervencija mogla biti opravdana, odsutna je iz kurikuluma.


# News Showcase: Zlatni kavez u hrvatskoj praksi

Google News Showcase lansiran u Hrvatskoj 2. veljače 2025. čini Hrvatsku 31. zemljom globalno i desetom u baltičko-srednjeeuropskoj regiji koja se pridružila programu. Inicijalno partnerstvo uključuje 24sata iz Styria Media Grupe kao najbolje prodavane hrvatske tabloidne novine sa snažnom digitalnom prisutnošću, Večernji list iz Hanza Media kao historijske hrvatske dnevne novine dio njemačkog austrijskog medijskog konglomerata s fokusom na premium sadržaj, Index.hr kao vodeći hrvatski digitalni portal neovisnog vlasništva iako ovisan o oglašavanju te Net.hr kao digitalni portal u vlasništvu CME Adria iz PPF Grupe.

Kritička analiza izbora partnera otkriva da četiri inicijalna partnera predstavljaju najveće hrvatske digitalne medije po dosegu publike. Tri su u vlasništvu stranih medijskih konglomerata, dok samo Index.hr predstavlja neovisno hrvatsko vlasništvo iako ostaje duboko ovisan o prihodu od oglašavanja duopola. Selekcija osobito isključuje manje regionalne portale poput Portal 072, ŠibenikIN i Zadarskog, neovisne istražne medije poput Telegrama i Lupige te specijalizirane izdavače uključujući poslovne medije, kulturne publikacije i medije na jezicima manjina.

Ova stratifikacija stvara algoritamske i ekonomske privilegije gdje partneri News Showcasea primaju izravno plaćanje u neotkrivenim iznosima, poboljšanu vidljivost u Google News, Discover i pretraživanju, showcase panele s premium vizualnim predstavljanjem, kontrolu kuriranja odabirom koji članci se pojavljuju te asocijaciju s Googleovim brendom legitimnosti. Isključeni izdavači se suočavaju s nultim dodatnim prihodom, konkurencijom protiv subvencioniranih showcase panela, algoritmičkim nedostatkom gdje showcase paneli vjerojatno primaju boostove angažmana te reputacijskim disparitetom.


Iznosi plaćanja kroz News Showcase ostaju komercijalno povjerljivi, no međunarodno izvještavanje pruža kontekst. Google je najavio globalnu investiciju od milijardu dolara u partnerstva s vijestima kroz tri godine od 2020. do 2023. produženu s dodatnim obvezama. Francuska je dobila 76 milijuna eura za licenciranje sadržaja vijesti od francuskih izdavača kroz tri godine, australski ugovori se kreću od 500 tisuća do nekoliko milijuna australskih dolara godišnje, britanski ugovori od 200 tisuća do nekoliko milijuna funti godišnje, dok brazilski ugovori s glavnim izdavačima kreću se između dva i pet milijuna dolara godišnje.

S obzirom na malu veličinu hrvatskog tržišta s populacijom od 3,8 milijuna i ukupnim tržištem digitalnog oglašavanja od 222 milijuna eura, News Showcase plaćanja individualnim izdavačima vjerojatno se kreću između 50 tisuća i 500 tisuća eura godišnje, s 24sata i Index.hr na višem kraju s obzirom na njihovu dominaciju u prometu. Ova plaćanja, iako značajna individualnim izdavačima, moraju se razumjeti u kontekstu. Googleovi prihodi od oglašavanja pretraživanjem u Hrvatskoj procijenjeni su na 96 milijuna eura godišnje, intermedijacija ad-tech u display oglašavanju zarobljavaju približno 25 do 35 milijuna eura od 81 milijuna eura tržišta display oglašavanja, a ukupna Googleova ekstrakcija prihoda iz Hrvatske procjenjuje se između 120 i 150 milijuna eura godišnje kroz pretraživanje, display intermedijaciju, YouTube, Google Cloud te Android i Play Store.

Ako News Showcase plaća kombinirano jedan do dva milijuna eura godišnje hrvatskim izdavačima, ovo predstavlja manje od dva posto Googleove ekstrakcije prihoda s hrvatskog tržišta. To nije redistribucija vrijednosti već mala naknada za licenciranje dok stroj za ekstrakciju nastavlja s operacijom. Javne izjave hrvatskih izdavača bile su univerzalno pozitivne, no analitička interpretacija tih izjava otkriva više slojeva značenja. Urednici naglašavaju kontrolu kuriranja, implicitno priznajući da je Googleovo algoritamsko kuriranje prethodno prioritiziralo sadržaj na temelju metrika angažmana koje mogu favorizirati senzacionalizam nad kvalitetom. Showcase nudi neko vraćanje uređivačke kontrole, ali samo unutar Googleovog okruženja.

Reference na sadržaj "sumnjive kvalitete" i "kvalitetno novinarstvo zaslužuje kvalitetnu prezentaciju" sugeriraju da izdavači gledaju na Showcase kao diferencijaciju od konkurenata niske kvalitete. Ipak, ova diferencijacija djeluje u potpunosti unutar Googleovog okvira, nije neovisno gradnja brenda već Google-posredovan prestiž. Javni entuzijazam reflektira pragmatičku stvarnost gdje izdavači koji se suočavaju s opadajućim prihodima ne mogu odbiti zajamčeno plaćanje. Kritika News Showcasea bi riskovala isključenje iz budućih Googleovih partnerstava.

# Photomath i ekstrakcija inovacije iz periferije


Akvizicija Photomatha, hrvatskog "jednorog" edukativne aplikacije, od strane Googlea 2023-24 predstavlja udžbenički primjer ekstrakcije iz centra prema periferiji. Photomath osnovan u Hrvatskoj 2014. postao je globalni uspjeh, edukativna aplikacija koja koristi računalni vid i umjetnu inteligenciju da rješava ručno napisane matematičke probleme, dosegnuvši preko 300 milijuna korisnika širom svijeta.

Javno je ovo proslavljeno kao hrvatska uspješna priča gdje su osnivači i investori uključujući Damir Sabol iz Day One Capital ostvarili lukrativno izlazak, a hrvatski inženjeri dobili zaposlenje u prestižnoj tehnološkoj divovskoj kompaniji. No, politička ekonomska analiza otkriva različite implikacije. Photomathove ključne tehnologije uključujući optičko prepoznavanje znakova za ručno napisanu matematiku, algoritme rješavanja problema i dizajn edukativnog sučelja sada su integrirani u Googleov AI stack. Značajke se pojavljuju u Google Lens koji rješava probleme kroz kameru, Gemini s matematičkim sposobnostima razmišljanja te Googleovim edukativnim ponudama.

Vrijednost koju Photomath generira sada pripada dioničarima Alphabeta i Googleovom globalnom ekosustavu proizvoda. Umjesto da se hrvatska kompanija natječe globalno, zarobljavajući međunarodne prihode i potencijalno usidrujući hrvatski tehnološki ekosustav kroz zapošljavanje stotina ljudi, mentoriranje startupa i demonstriranje mogućnosti skaliranja, Photomathova ekstrakcija vrijednosti preselila se u Kaliforniju. Ovo pojačava dinamiku "podružničnog pogona" gdje hrvatski IT talent sve više gleda na izlazak kroz akviziciju od big tech kao optimalan ishod umjesto gradnje neovisnih globalnih konkurenata.

Ova dinamika stvara samoispunjavajuće proročanstvo. Talentirani inženjeri žele se pridružiti potencijalnim "jednorožićima" koji će vjerojatno biti kupljeni, investitori financiraju startupe s potencijalom izlaska umjesto dugoročnom neovisnošću, sveučilišta i akceleratori obučavaju talent za integraciju u globalne platforme umjesto za disrupciju platformi, a javna politika slavi akvizicije kao "uspjeh" umjesto gubitka suverene tehnološke kapaciteta. IT sektor Hrvatske, unatoč visokim razinama talenta, sve više funkcionira kao "podružnički pogon" koji pruža tehnološke usluge stranim platformama umjesto razvijanja konkurentskih platformi.

# Regulatorni okviri i asimetrične jurisdikcije

Hrvatska država pokušava regulirati medijsko tržište da osigura pluralizam i transparentnost, no nedostaje joj jurisdikcija da efektivno regulira primarnog aktora na tom tržištu. U travnju 2025., Agencija za elektroničke medije lansirala je Platformu vlasništva i financiranja medija koja prisiljava hrvatske medijske kuće da otkriju konačne vlasnike i izvore financiranja, povezane transakcije radi identifikacije sukoba interesa te promjene u vlasništvu radi praćenja konsolidacije.

Demokratska vrijednost ove platforme je značajna jer se bavi pravim problemom gdje hrvatski mediji su patili od neprozirnog vlasništva koje omogućava politički utjecaj, pranje novca i sukobe interesa. Primjeri uključuju lokalne medijske kuće tajno u vlasništvu političkih figura, primatelje javnih subvencija bez transparentnog konačnog vlasništva, strukture preklapajućeg vlasništva koje zamagljuju koncentraciju te strano vlasništvo kroz kompleksne korporativne strukture.

No, kritično ograničenje je da se regulacija primjenjuje samo na hrvatske pravne entitete. Prisiljavaju Index.hr ili Narod.hr da budu transparentni, ali ne može i ne prisiljavaju Google da bude transparentan o vlasništvu svojih algoritamskih odluka, ad-tech intermedijaciji gdje točne naknade koje Google naplaćuje na svakoj fazi transakcije ostaju netransparentne, prikupljanju i korištenju podataka gdje ostaje nejasno koje bihevioralne podatke Google prikuplja o hrvatskim korisnicima i kako se koriste, alokaciji prihoda gdje ostaje nejasno koliko točno novca Google ekstrahira s hrvatskog tržišta oglašavanja te stranom vlasništvu nad kuriranjem sadržaja gdje Googleove strukture sa sjedištem u Dublinu određuju koje informacije hrvatski građani vide.

Asimetrija stvara regulatornu zastarjelost gdje okviri dizajnirani za medije dvadesetog stoljeća poput emitera i novina primjenjuju se na platforme dvadeset prvog stoljeća koje koncentriraju moć kroz fundamentalno različite mehanizme uključujući algoritme, podatke i infrastrukturu. Implementacija Zakona o digitalnim uslugama Europske unije doživjela je značajna kašnjenja. Dok je Hrvatska odredila HAKOM kao Koordinatora digitalnih usluga, implementacija je suočena s zakonodavnim prazninom gdje Hrvatska do kraja 2024. i početka 2025. nije donijela specifično nacionalno zakonodavstvo koje HAKOM-u daje mehanizme provedbe, procedure za pritužbe i strukture kazni potrebne za implementaciju DSA-a.

Resursna ograničenja također opterećuju implementaciju. HAKOM historijski fokusiran na telekomunikacijsku regulaciju nema specijaliziranu ekspertizu u platformskim algoritamskim sustavima, moderaciji sadržaja u velikoj skali i procjeni rizika umjetne inteligencije. HND i SNH kritizirali su kašnjenja implementacije, primjećujući da bez robusne provedbe, hrvatski građani nemaju praktičan pravni lijek za nepravedno algoritamsko degradiranje sadržaja, diskriminatorne odluke o moderaciji sadržaja, dezinformacije koje ciljaju hrvatske izbore ili transparentnost u to zašto se sadržaj pojačava ili potiskuje.

Ulog za medije je visok jer bi provedba DSA mogla pružiti hrvatskim izdavačima zahtjeve za transparentnošću algoritama koji prisiljavaju Google da objasni faktore rangiranja, pristup podacima omogućavajući istraživanje kako promjene algoritma utječu na promet, mehanizme za pritužbe kada izdavači vjeruju da su nepravedno tretirani te kazne sa zubima do šest posto godišnjeg globalnog prihoda za kršenja. Bez implementacije, ova ostaju teorijska prava umjesto praktičnih pravnih lijekova.

# Hrvatska potrošačka ponašanja i erozija izravnog pristupa

Hrvatska pokazuje distinktivnu obrazac konzumacije vijesti koji djelomično ublažava Googleove efekte čuvanja. Tržišna analiza i podaci Reuters Instituta primjećuju da hrvatski korisnici imaju jaku naviku izravnog odlaska na portale vijesti umjesto oslanjanja na tražilice ili društvene medije za otkrivanje vijesti. Reuters Institute Digital News Report nalazi da 90 posto Hrvata čita vijesti online među najvišima u EU, izjednačeno samo s Finskom na 93 posto, pri čemu izravni pristup etabliranim portalima ostaje značajan.

Index.hr, 24sata, Jutarnji list i Večernji list zapovjeduju snažnom izravnom lojalnošću publike. Društveni mediji za vijesti dosižu 56 posto populacije što je značajno ali ne dominantno, dok Facebook predstavlja 81 posto konzumacije vijesti društvenih medija. "Navika portala" se očituje kako mnogi Hrvati, posebno starije demografije, imaju ustanovljene dnevne rutine uključujući jutarnju provjeru početne stranice Index.hr ili 24sata, bookmarkove ili prečace na početnom ekranu mobilnih uređaja, lojlalnost brenda specifičnim medijima te izravno upisivanje URL-a ili spremljene linkove.

Ovaj djelomičan efekt amortizatora znači da promjene algoritma mogu imati manje neposrednog utjecaja na etablirane izdavače nego na tržištima poput SAD-a ili Velike Britanije gdje pretraživanje i društveni mediji dominiraju otkrivanjem vijesti. Ako hrvatski medij izgubi 30 posto prometa Google pretraživanja, može preživjeti na izravnom prometu, dok bi potpuno ovisni izdavač o pretraživanju suočio krizu. No, navika izravnog pristupa pokazuje znakove erozije. Reuters Institute istraživanje dokumentira da korisnici mlađi od 35 godina značajno vjerojatnije otkrivaju vijesti kroz društvene medije gdje algoritamski feedovi površe vijesti bez lojalnosti portalu, Google Discover gdje personalizirani feed predstavlja priče iz više izvora, YouTube gdje video sadržaj dolazi od profesionalnih medija i neovisnih kreatora te agregaciju vijesti gdje aplikacije poput Google News i Apple News konsolidiraju iz više izvora.

Mobilno-prvo ponašanje posebno među mlađim kohortama pokazuje različite obrasce. Manje vjerojatno upisuju URL-ove izravno, vjerojatnije prihvaćaju zadane aplikacije i feedove, veće oslanjanje na algoritamsku preporuku te kraća razdoblja pažnje favorizirajuća konzumacija naslova u feedovima. Kako starije kohorte koje su uspostavile navike portala stare, mlađe kohorte bez tih navika postaju primarne konzumente vijesti. Trenutni dvadesetogodišnjaci možda nikada neće razviti snažne lojalnosti izravnom portalu, oslanjajući se potpuno na algoritamsku intermedijaciju.

Projekcija sugerira da je amortizator izravnog pristupa koji štiti hrvatske izdavače vremenski ograničen. Unutar 10 do 15 godina, generacijska promjena mogla bi eliminirati ovu distinktivnu hrvatsku karakteristiku, ostavljajući izdavače jednako ovisne o Googleovim algoritmima kao njihove zapadnoeuropske kolege. Čak i za izdavače koji trenutno profitiraju od izravnog prometa, ovo samo ne može osigurati održivost. Izravni promet predstavlja postojeće publike, ali rast publike esencijalan za poslovnu održivost zahtijeva vidljivost u pretraživanju kontroliranu od Googlea, doseg u društvenim medijima kontroliran od Mete i TikToka te selekciju Discover feeda kontroliranu od Googlea.

# Put naprijed

Ova analiza dokumentirala je kako Google funkcionira u Hrvatskoj ne kao tržišni sudionik već kao infrastrukturni suveren koji izvršava moć nad digitalnim teritorijom analognu državnoj suverenosti nad fizičkim teritorijem. Google kontrolira distribucijsku infrastrukturu kroz pretraživanje sa 97,02 posto tržišnog udjela, Android kao mobilni operacijski sustav čuvar, Chrome sa 64 do 72 posto globalnog udjela za kontrolu podataka i standarda na razini preglednika te YouTube sa 82,7 posto dosega u Hrvatskoj kao monopol video sadržaja.

Ekonomska infrastruktura je jednako zarobljavajuća kroz ad-tech stack koji je vertikalno integriran za ekstrakciju iz programatskog oglašavanja, oglašavanje pretraživanjem koje kanalizira 96 milijuna eura godišnje izravno Googleu, ad-tech porez koji zarobljavaju 49 do 70 posto display oglašivačkih transakcija te monopol podataka gdje bihevioralni višak koji hrvatski izdavači ne mogu pristupiti ili monetizirati teče Googleu. Kognitivna infrastruktura uključuje algoritamsko kuriranje koje određuje koji sadržaj publike vide, obuku umjetne inteligencije koja koristi hrvatski sadržaj bez kompenzacije, AI Overviews koji zamjenjuju promet izdavača sa sintezom hostiranom od Googlea te News Showcase kao selektivnu subsidizaciju koja stvara ovisna partnerstva.

Stupica suvereniteta znači da hrvatski izdavači suočavaju nemogući položaj. Ne mogu funkcionirati bez Googleove infrastrukture što predstavlja tehničku ovisnost, ne mogu se natjecati s Googleovim prednostima podataka što stvara ekonomski nedostatak, ne mogu efektivno izazivati Googleove prakse što rezultira političkom impotencijom te ne mogu izgraditi alternativnu infrastrukturu zbog nedostatka resursa. Ovo predstavlja ono što znanstvenici nazivaju infrastrukturni imperijalizam, kontrolu ne kroz politički osvajanje već kroz vlasništvo esencijalne infrastrukture za ekonomsko i društveno sudjelovanje.

Ekonomski tokovi dokumentirani u ovom izvještaju otkrivaju sistematsku ekstrakciju vrijednosti. Hrvatski proizvođači sadržaja uključujući novinare, urednike i izdavače ulažu rad, ekspertizu i resurse u kreaciju sadržaja, snose troškove novinarstva kroz plaće, infrastrukturu i pravne rizike te preuzimaju građansku odgovornost kroz odgovornost novinarstvo i verificirane informacije. Googleova uloga uključuje indeksiranje sadržaja bez kompenzacije, intermedijaciju oglašavanja s ekstrakcijom od 49 do 70 posto, prikupljanje bihevioralnih podataka dok uskraćuje pristup izdavačima, sintetiziranje sadržaja u AI sustavima bez licenciranja te kontrolu distribucije kroz algoritamsku neprozirnost.

Akumulacija vrijednosti teče na predvidljiv način gdje hrvatski izdavači doživljavaju opadajuće prihode i prekarnu održivost dok dioničari Googlea zarobljavaju procijenjenih 120 do 150 milijuna eura godišnje samo s hrvatskog tržišta. Ovo predstavlja ekstrakciju centar-periferija gdje sirovine u obliku novinarstva i korisničkih podataka proizvode se na periferiji u Hrvatskoj, procesiranje dodavanja vrijednosti kroz analizu podataka, sustave ciljanja i obuku umjetne inteligencije događa se u centru u Kaliforniji i Dublinu, gotovi proizvodi uključujući rezultate pretraživanja, AI sažetke i ciljane oglase prodaju se natrag periferiji, a profiti akumuliraju u centru.

Slogan "Rasti s Googleom" u ovom svjetlu čita se manje kao ekonomski razvoj i više kao kolonijalna administracija, upravljanje provincijom bogatom resursima radi maksimiziranja efikasnosti ekstrakcije. News Showcase predstavlja sofisticirani mehanizam za upravljanje nesuglasjem izdavača dok očuvava ekstraktivnu arhitekturu. Kratkoročno olakšanje kroz zajamčena plaćanja od procijenjenih 50 tisuća do 500 tisuća eura godišnje pruža ključni prihod, poboljšana vidljivost u algoritmima nudi koristi prometa, a asocijacija s Googleovim brendom pruža legitimnost.


No, dugoročna ovisnost produbljuje integraciju u Googleov ekosustav povećavajući troškove izlaska, ekonomska ovisnost smanjuje zagovaranje za strukturne reforme, tržišna stratifikacija privilegira odabrane partnere stavljajući u nepovoljan položaj isključene izdavače, a stvara podršku dionika za Googleove regulatorne pozicije. Ugovori su "dobrovoljni" u istom smislu u kojem se osoba koja se davi "dobrovoljno" hvata za plovak, izbor je tehnički slobodan ali alternative su nemoguće. Ključno je da plaćanja News Showcasea predstavljaju manje od dva posto Googleove ekstrakcije prihoda iz Hrvatske, ovo nije redistribucija vrijednosti već minimalno licenciranje da deflektira zahtjeve za strukturnom promjenom gdje izdavači primaju mrvice dok stroj za ekstrakciju nastavlja s operacijom.

Uvođenje AI Overviews predstavlja ono što promatrači industrije nazivaju "događaj na razini izumiranja" za digitalnu izdavačku industriju. Studije dokumentiraju pad prometa od 30 do 80 posto kada se pojavljuju AI Overviews, rast pretraživanja bez klikova sa 56 posto na 69 posto između svibnja 2024. i svibnja 2025., devastaciju prihoda gdje je programatsko oglašavanje ovisno o pregledima stranica što znači da urušavanje prometa jednači urušavanje prihoda, eroziju atribucije gdje korisnici asociraju informacije s "AI" umjesto izdavačima te ekstrakciju intelektualnog vlasništva gdje se sadržaj koristi bez kompenzacije ili pristanka.

Za hrvatske izdavače koji već djeluju s tankim maržama, pad prometa od 30 do 40 posto mogao bi prisiliti zatvaranja. Manji mediji nemaju resurse da adaptiraju ili litigiraju, a cijeli poslovni model proizvesti sadržaj da privuče promet da proda oglase lomi se. Pitanje transformacije je esencijalno, ali hoće li ovo prisiliti evoluciju prema pretplatničkim modelima gdje Hrvati neće platiti, javnom financiranju gdje rizici političkog zarobljavanja postoje, newsletter i zajedničkim modelima koji nude ograničenu skalu, non-profit novinarstvu koje zahtijeva bazu donatora ili produbljivanju platformske ovisnosti gdje izbor postaje prihvatiti uvjete News Showcasea ili umrijeti? Nijedna od ovih alternativa trenutno ne izgleda održivo u skali potrebnoj da održi hrvatski medijski pluralizam.

Postojeći regulatorni okviri nude neku zaštitu ali ostaju nedovoljni. Ono što funkcionira uključuje provedbu EU DMA gdje zabrane samopreferiranja mogu poboljšati organsku vidljivost u pretraživanju, antitrust za ad-tech gdje je kazna od 2,95 milijardi eura iz rujna 2025. s prijetnjom strukturnog pravnog lijeka značajna, okvir DSA gdje zahtjevi za transparentnošću algoritma i procjene rizika su korisni te precedente američkog antitrusta gdje su presude iz kolovoza 2024. i travnja 2025. ustanovile nezakonitu monopolizaciju.

No ono što nedostaje je podjednako značajno. Pravoče implementacija hrvatskog DSA zahtijeva da HAKOM dobije zakonodavno osnaženje i resurse, obavezna kompenzacija za obuku AI stvara pravno pravo na plaćanje za korištenje sadržaja, označavanje common carrier tretirajući infrastrukturu pretraživanja kao esencijalnu olakšicu zahtijevajući nediskriminirajući pristup, algoritmi javnog interesa zahtijevajući optimizaciju za kvalitetu informacija nad angažmanom te provedba prenosivosti podataka omogućavajući izdavačima pristup bihevioralnim podacima o njihovim publikama.

Strukturni izazov je da regulacija pokušava ograničiti monopolsko ponašanje dok ostavlja monopolsku strukturu netaknutom. Fundamentalniji pristupi mogli bi uključivati strukturnu separaciju prisiljavajući Google da se riješi Chromea, razdvoji ad-tech poslove i razdvoji pretraživanje od oglašavanja, javnu digitalnu infrastrukturu kroz financiranje vlade za alternative Googleovim uslugama, kooperativne modele gdje izdavači posjeduju oglašivačke burze i podatkovne platforme te regulaciju platformske korisnosti tretirajući digitalnu infrastrukturu poput električne energije s reguliranim nediskriminirajućim pristupom i obvezama javnog interesa.

Hrvatska država suočava se s teškim ograničenjima. Jurisdikcijska ograničenja znače da Hrvatska ne može efektivno regulirati korporaciju sa sjedištem u Kaliforniji operira kroz strukture u Dublinu, nacionalni zakon dostiže hrvatske entitete ali ne stranu platformu koja kontrolira tržište. Asimetrija resursa je također problematična jer je cijeli regulatorni proračun Hrvatske red veličine manji od budžeta pravnog odjela Googlea. Ovisnost o EU za značajnu regulaciju zahtijeva rad kroz procese Europske komisije, ograničavajući izravnu kontrolu.

Ekonomska vulnerabilnost znači da agresivna akcija protiv Googlea riskira algoritamsku odmazdu kroz degradiranje hrvatskih stranica, povlačenje usluge gdje Google gasi usluge u Hrvatskoj, odvraćanje investicija kroz percepciju "neprijateljstva prema tech kompanijama" te gubitak programa obuke "Rasti s Googleom". Ograničene poluge uključuju javno financiranje medija kroz ekspanziju podrške AEM-a novinarstvu uz pažljiv dizajn da izbjegne političko zarobljavenje, snažnu implementaciju DSA osnažujući HAKOM kapacitetom provedbe, obrazovanje o medijskoj pismenosti podučavajući kritičku svijest o platformama, podršku za alternative financiranje razvoja hrvatske ili EU digitalne infrastrukture te agresivno zagovaranje u EU guranje za snažnu provedbu DMA i DSA te razmatranje strukturnih pravnih lijekova.

Bez značajne intervencije, putanja prema 2030. izgleda sumorno. Scenarij šuplje ljuske predviđa da AI Overviews eliminiraju 40 do 60 posto prometa izdavača, hrvatski mediji postaju farme sadržaja koje hrane Googleovu umjetnu inteligenciju, News Showcase se širi ali plaćanja ostaju mali udio ekstrahirane vrijednosti, veliki izdavači preživljavaju kao ovisni partneri Googlea, manji mediji zatvaraju stvarajući novinske pustinje, medijski pluralizam kolabira kako samo Google-odabrani partneri preživljavaju, a informacijski suverenitet efektivno transferira stranoj korporaciji.

Reformirani ekosustav scenarij zahtijeva agresivnu intervenciju kroz provedbu DMA i DSA koja prisiljavaju transparentnost algoritma i pravedno dijeljenje prihoda, strukturnu separaciju ad-tech koja smanjuje stope ekstrakcije, obavezno licenciranje AI koje stvara mehanizme kompenzacije, javnu digitalnu infrastrukturu koja pruža održive alternative, snažnu hrvatsku implementaciju koja omogućava efektivno pravno ljekovanje izdavača, programe podrške medijima pažljivo dizajnirane da održe lokalno novinarstvo te kooperativne platforme izdavača koje omogućavaju pooling podataka i pregovaračku moć.

Najvjerojatniji ishod bez radikalne promjene je spor upravljen pad hrvatske medijske neovisnosti, rastuća koncentracija oko nekoliko velikih pretežno stranih izdavača, rastuće novinske pustinje u regionalnoj Hrvatskoj, rastuća ovisnost o Googleovoj infrastrukturi i partnerstvima, erozija novinarskog kvaliteta kako ekonomski pritisci intenzivniraju te demokratski informacijski deficit posebno utječući na lokalnu odgovornost.

Ovaj studij slučaja Googlea u Hrvatskoj validira i proširuje kritičke okvire političke ekonomije. Smytheova roba publike našla je svoju perfektnu realizaciju u digitalnom dobu gdje je komodifikacija pažnje dovršena. Hrvatska publika izvršava digitalni rad generirajući bihevioralne podatke koje Google monetizira dok izdavači primaju opadajuće udjele. Fuchsov digitalni rad objašnjava kako su korisnici istovremeno proizvodi prodani oglašivačima, radnici generirajući vrijedne podatke i sirovine s obrasci ponašanja ekstrahirani i rafinirani.

Digitalni kolonijalizam objašnjava Googleove operacije gdje kontroliranje infrastrukture, aproprijacija podataka i inovacije te zarobljavanja vrijednosnih lanaca djeluju dok periferijska tržišta pružaju inpute i konzumaciju. Nadzorni kapitalizam Shoshane Zuboff objašnjava Googleov poslovni model ekstrahirajući bihevioralni višak iznad onog potrebnog za poboljšanje usluge, konvertirajući ga u proizvode predviđanja i prodajući bilo kojem entitetu tražeći utjecati ili predvidjeti ljudsko ponašanje. Platformski kapitalizam Nick Srniceka primjenjuje se savršeno gdje Google ne proizvodi novinarstvo ali kontrolira i monetizira infrastrukturu kroz koju novinarstvo dostiže publike.

Pozicija polu-periferije Hrvatske, visoka digitalna povezanost, educirana populacija i članstvo u EU ali malo tržište i kapitalna ograničenja, stvara specifične vulnerabilnosti. Polu-periferne regije često se suočavaju s najgorim oba svjeta, dovoljno napredne da budu vrijedne mete ekstrakcije za razliku od nepovezane periferije, premale da razviju konkurentsku infrastrukturu za razliku od centralnih regija, te dovoljni resursi da prepoznaju eksploataciju ali nedovoljni da joj se odupru.

Konačna presuda je da Googleova uloga u hrvatskim medijima je ona hegemona. Uspješno je zarobljavao distribuciju, monetizaciju, rad i inovaciju. Partnerstvo ponuđeno kroz News Showcase pruža mehanizme preživljavanja za odabrane izdavače, ali ih zaključava u podređene pozicije, više nisu neovisni navigatori otvorenog weba već stanari farmeri na Googleovoj digitalnoj zemlji plaćajući rentu u obliku podataka i autonomije.

Politička ekonomija je eksplicitno ekstraktivna gdje vrijednost teče s hrvatske periferije prema digitalnom centru. Stupica suvereniteta znači da čak i dobro namjerne regulacije poput Platforme vlasništva medija ne dotiču pravi lokus moći. Izbor pred hrvatskim izdavačima, kreatorima politika i građanima je oštar. Prihvatiti produbljavanje ovisnosti znači nastaviti adaptirati Googleovim zahtjevima nadajući se da News Showcase plaćanja pružaju dovoljnu podršku životu prihvaćajući postupnu eroziju medijske neovisnosti i transformaciju u pružatelje sadržaja za AI sustave u vlasništvu stranih korporacija.

Zahtijevati strukturnu reformu znači organizirati se kolektivno da zahtijeva agresivnu provedbu EU sa strukturnim pravnim lijekovima uključujući prodaju Chromea i separaciju ad-tech, obaveznu kompenzaciju za obuku AI na novinarskom sadržaju, označavanje common carrier za infrastrukturu pretraživanja, transparentnost algoritma sa značajnim pravnim lijekovima izdavača, investiciju u javnu digitalnu infrastrukturu te snažnu hrvatsku implementaciju DSA sa kapacitetom provedbe.

Prvi put je put upravljanog pada. Drugi zahtijeva političku mobilizaciju, europsku solidarnost i konfrontaciju s jednom od najmoćnijih korporacija svijeta. Akademska literatura o društvenim pokretima sugerira da promjena postaje moguća kada se tri uvjeta usklađuju: svijest ili razumijevanje strukturne prirode problema gdje ovaj izvještaj pridonosi, organizacija ili kapacitet kolektivne akcije kroz HUDI, HND i europska udruženja izdavača te politička prilika ili regulatorni trenutak kada je intervencija izvediva gdje pobjede američkog antitrusta i provedba EU DMA i DSA stvaraju ovo otvaranje.

Regulatorni momentum 2024. do 2025. uključujući antitrust osude, kazne od nekoliko milijardi eura i prijedloge strukturnih pravnih lijekova, sugerira da se prozor za fundamentalnu reformu možda otvara. Hoće li hrvatski medijski dionici, europski regulatori i civilno društvo moći koordinirati efektivno da prođu kroz njega odredit će vidi li 2030. održiv, pluralistički, demokratski hrvatski medijski ekosustav ili šuplju ljusku koja služi interesima Alphabet Inc. umjesto hrvatskom javnom diskursu.

Slogan "Rasti s Googleom" bit će suđen poviješću ne po Googleovim namjerama već po njegovim efektima. Je li Hrvatska rasla kao neovisna digitalna ekonomija sa suverenim kapacitetom, ili je rasla dublje u ovisnost o stranoj infrastrukturi dok su njezine medijske institucije venule? Odgovor ovisi o izborima napravljenim u sljedećih nekoliko godina.






























